# CyberViser — Funding & Sponsorship
# These are the supported funding platforms for Hancock.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [cyberviser]
ko_fi: cyberviser
open_collective: cyberviser
buy_me_a_coffee: cyberviser
patreon: cyberviser
custom: ["https://cyberviser.ai/sponsors"]
