homepage: "https://github.com/0ai-Cyberviser/Hancock"
language: python
primary_contact: "cyberviser@proton.me"
auto_ccs:
  - "security@cyberviser.ai"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: "https://github.com/0ai-Cyberviser/Hancock"
