apiVersion: v1
kind: Service
metadata:
  name: hancock
  namespace: hancock
  labels:
    app: hancock
    app.kubernetes.io/name: hancock
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  type: ClusterIP
  selector:
    app: hancock
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
