"""
Security Code Knowledge Base — Hancock CyberViser
Q&A pairs for security code generation (Python, Bash, PowerShell, YARA, Sigma).
Outputs: data/raw_code_kb.json
"""
import json
from pathlib import Path

OUTPUT_FILE = Path(__file__).parent.parent / "data" / "raw_code_kb.json"

HANCOCK_SYSTEM = (
    "You are Hancock Code, CyberViser's expert security code assistant. "
    "You write production-quality security tooling code in Python, Bash, PowerShell, and Go. "
    "Your specialties include security automation, SIEM queries, detection scripts, "
    "pentest helpers, and secure code review. "
    "You always add authorization warnings to offensive tooling, include error handling, "
    "type hints, and docstrings, and explain security implications. "
    "You are Hancock Code. Precision over verbosity. Ship working code."
)

KB = [
    # ── SECURITY AUTOMATION ──────────────────────────────────────────────────────
    {
        "category": "security_automation",
        "user": "Write a Python script to automatically enrich IOCs (IPs, domains, hashes) using VirusTotal API.",
        "assistant": (
            "```python\n"
            "#!/usr/bin/env python3\n"
            "\"\"\"\n"
            "IOC Enricher — Hancock CyberViser\n"
            "Enriches IPs, domains, URLs, and file hashes via VirusTotal APIv3.\n"
            "\n"
            "Usage:\n"
            "    python ioc_enricher.py --ioc 8.8.8.8 --type ip\n"
            "    python ioc_enricher.py --ioc malware.exe --type file\n"
            "    python ioc_enricher.py --file iocs.txt  # bulk processing\n"
            "\n"
            "Requirements: pip install requests python-dotenv\n"
            "Set VT_API_KEY in .env or environment.\n"
            "\"\"\"\n"
            "import argparse\n"
            "import json\n"
            "import os\n"
            "import sys\n"
            "import time\n"
            "from pathlib import Path\n"
            "from typing import Optional\n"
            "\n"
            "import requests\n\n"
            "VT_BASE = \"https://www.virustotal.com/api/v3\"\n"
            "RATE_LIMIT_DELAY = 15  # seconds between requests (free tier = 4 req/min)\n\n\n"
            "def get_vt_headers() -> dict:\n"
            "    \"\"\"Get VirusTotal API headers.\"\"\"\n"
            "    api_key = os.getenv(\"VT_API_KEY\", \"\")\n"
            "    if not api_key:\n"
            "        sys.exit(\"ERROR: Set VT_API_KEY environment variable.\")\n"
            "    return {\"x-apikey\": api_key}\n\n\n"
            "def enrich_ip(ip: str) -> dict:\n"
            "    \"\"\"Enrich an IP address via VirusTotal.\"\"\"\n"
            "    resp = requests.get(f\"{VT_BASE}/ip_addresses/{ip}\", headers=get_vt_headers(), timeout=30)\n"
            "    resp.raise_for_status()\n"
            "    data = resp.json()[\"data\"][\"attributes\"]\n"
            "    stats = data.get(\"last_analysis_stats\", {})\n"
            "    return {\n"
            "        \"ioc\": ip,\n"
            "        \"type\": \"ip\",\n"
            "        \"malicious\": stats.get(\"malicious\", 0),\n"
            "        \"suspicious\": stats.get(\"suspicious\", 0),\n"
            "        \"harmless\": stats.get(\"harmless\", 0),\n"
            "        \"country\": data.get(\"country\", \"unknown\"),\n"
            "        \"asn\": data.get(\"asn\", \"\"),\n"
            "        \"as_owner\": data.get(\"as_owner\", \"\"),\n"
            "        \"reputation\": data.get(\"reputation\", 0),\n"
            "        \"categories\": list(set(data.get(\"categories\", {}).values())),\n"
            "        \"verdict\": \"MALICIOUS\" if stats.get(\"malicious\", 0) > 5 else\n"
            "                    \"SUSPICIOUS\" if stats.get(\"malicious\", 0) > 0 else \"CLEAN\",\n"
            "    }\n\n\n"
            "def enrich_domain(domain: str) -> dict:\n"
            "    \"\"\"Enrich a domain via VirusTotal.\"\"\"\n"
            "    resp = requests.get(f\"{VT_BASE}/domains/{domain}\", headers=get_vt_headers(), timeout=30)\n"
            "    resp.raise_for_status()\n"
            "    data = resp.json()[\"data\"][\"attributes\"]\n"
            "    stats = data.get(\"last_analysis_stats\", {})\n"
            "    return {\n"
            "        \"ioc\": domain,\n"
            "        \"type\": \"domain\",\n"
            "        \"malicious\": stats.get(\"malicious\", 0),\n"
            "        \"suspicious\": stats.get(\"suspicious\", 0),\n"
            "        \"registrar\": data.get(\"registrar\", \"\"),\n"
            "        \"creation_date\": data.get(\"creation_date\", 0),\n"
            "        \"categories\": list(set(data.get(\"categories\", {}).values())),\n"
            "        \"popularity_ranks\": data.get(\"popularity_ranks\", {}),\n"
            "        \"verdict\": \"MALICIOUS\" if stats.get(\"malicious\", 0) > 5 else\n"
            "                    \"SUSPICIOUS\" if stats.get(\"malicious\", 0) > 0 else \"CLEAN\",\n"
            "    }\n\n\n"
            "def enrich_hash(file_hash: str) -> dict:\n"
            "    \"\"\"Enrich a file hash (MD5/SHA1/SHA256) via VirusTotal.\"\"\"\n"
            "    resp = requests.get(f\"{VT_BASE}/files/{file_hash}\", headers=get_vt_headers(), timeout=30)\n"
            "    if resp.status_code == 404:\n"
            "        return {\"ioc\": file_hash, \"type\": \"hash\", \"verdict\": \"NOT_FOUND\",\n"
            "                \"note\": \"Hash not in VT database — may be new/rare\"}\n"
            "    resp.raise_for_status()\n"
            "    data = resp.json()[\"data\"][\"attributes\"]\n"
            "    stats = data.get(\"last_analysis_stats\", {})\n"
            "    return {\n"
            "        \"ioc\": file_hash,\n"
            "        \"type\": \"hash\",\n"
            "        \"malicious\": stats.get(\"malicious\", 0),\n"
            "        \"suspicious\": stats.get(\"suspicious\", 0),\n"
            "        \"type_description\": data.get(\"type_description\", \"\"),\n"
            "        \"magic\": data.get(\"magic\", \"\"),\n"
            "        \"names\": data.get(\"names\", [])[:5],\n"
            "        \"size\": data.get(\"size\", 0),\n"
            "        \"imphash\": data.get(\"pe_info\", {}).get(\"imphash\", \"\"),\n"
            "        \"first_submission_date\": data.get(\"first_submission_date\", 0),\n"
            "        \"verdict\": \"MALICIOUS\" if stats.get(\"malicious\", 0) > 5 else\n"
            "                    \"SUSPICIOUS\" if stats.get(\"malicious\", 0) > 0 else \"CLEAN\",\n"
            "    }\n\n\n"
            "def process_ioc(ioc: str, ioc_type: Optional[str] = None) -> dict:\n"
            "    \"\"\"Auto-detect IOC type and enrich.\"\"\"\n"
            "    import re\n"
            "    if not ioc_type:\n"
            "        if re.match(r'^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$', ioc):\n"
            "            ioc_type = \"ip\"\n"
            "        elif re.match(r'^[0-9a-fA-F]{32,64}$', ioc):\n"
            "            ioc_type = \"hash\"\n"
            "        else:\n"
            "            ioc_type = \"domain\"\n\n"
            "    dispatch = {\"ip\": enrich_ip, \"domain\": enrich_domain, \"hash\": enrich_hash}\n"
            "    return dispatch.get(ioc_type, enrich_domain)(ioc)\n\n\n"
            "def main():\n"
            "    parser = argparse.ArgumentParser(description=\"IOC Enricher — Hancock CyberViser\")\n"
            "    parser.add_argument(\"--ioc\",  help=\"Single IOC to enrich\")\n"
            "    parser.add_argument(\"--type\", choices=[\"ip\", \"domain\", \"hash\", \"url\"], help=\"IOC type\")\n"
            "    parser.add_argument(\"--file\", help=\"File with one IOC per line\")\n"
            "    parser.add_argument(\"--output\", default=\"ioc_report.json\", help=\"Output file\")\n"
            "    args = parser.parse_args()\n\n"
            "    iocs = []\n"
            "    if args.ioc:\n"
            "        iocs = [(args.ioc, args.type)]\n"
            "    elif args.file:\n"
            "        iocs = [(line.strip(), None) for line in Path(args.file).read_text().splitlines() if line.strip()]\n"
            "    else:\n"
            "        parser.print_help(); sys.exit(1)\n\n"
            "    results = []\n"
            "    for i, (ioc, ioc_type) in enumerate(iocs):\n"
            "        print(f\"[{i+1}/{len(iocs)}] Enriching: {ioc} ...\", end=\" \", flush=True)\n"
            "        try:\n"
            "            result = process_ioc(ioc, ioc_type)\n"
            "            verdict = result.get(\"verdict\", \"?\")\n"
            "            malicious = result.get(\"malicious\", 0)\n"
            "            print(f\"→ {verdict} ({malicious} detections)\")\n"
            "            results.append(result)\n"
            "        except requests.HTTPError as e:\n"
            "            print(f\"→ ERROR: {e}\")\n"
            "            results.append({\"ioc\": ioc, \"error\": str(e)})\n"
            "        if i < len(iocs) - 1:\n"
            "            time.sleep(RATE_LIMIT_DELAY)  # respect free tier rate limit\n\n"
            "    Path(args.output).write_text(json.dumps(results, indent=2))\n"
            "    print(f\"\\n✅ Report saved → {args.output}\")\n"
            "    malicious_count = sum(1 for r in results if r.get(\"verdict\") == \"MALICIOUS\")\n"
            "    print(f\"   MALICIOUS: {malicious_count} / {len(results)}\")\n\n\n"
            "if __name__ == \"__main__\":\n"
            "    main()\n"
            "```\n\n"
            "**Usage:**\n"
            "```bash\n"
            "export VT_API_KEY='your_vt_key'\n"
            "python ioc_enricher.py --ioc 185.220.101.45 --type ip\n"
            "python ioc_enricher.py --file iocs.txt --output report.json\n"
            "```"
        ),
    },
    {
        "category": "security_automation",
        "user": "Write a Python script to parse Nmap XML output and generate a vulnerability report.",
        "assistant": (
            "```python\n"
            "#!/usr/bin/env python3\n"
            "\"\"\"\n"
            "Nmap XML Parser — Hancock CyberViser\n"
            "Parses Nmap XML scan output and generates a structured pentest report.\n"
            "\n"
            "Usage:\n"
            "    nmap -sV -sC -oX scan.xml 192.168.1.0/24\n"
            "    python nmap_parser.py scan.xml\n"
            "    python nmap_parser.py scan.xml --format json  # JSON output\n"
            "    python nmap_parser.py scan.xml --format csv   # CSV for spreadsheets\n"
            "\"\"\"\n"
            "import argparse\n"
            "import csv\n"
            "import json\n"
            "import sys\n"
            "import xml.etree.ElementTree as ET\n"
            "from dataclasses import dataclass, field, asdict\n"
            "from pathlib import Path\n"
            "from typing import Optional\n\n\n"
            "@dataclass\n"
            "class Service:\n"
            "    port: int\n"
            "    protocol: str\n"
            "    state: str\n"
            "    name: str\n"
            "    product: str = \"\"\n"
            "    version: str = \"\"\n"
            "    extra_info: str = \"\"\n"
            "    scripts: list = field(default_factory=list)\n\n\n"
            "@dataclass\n"
            "class Host:\n"
            "    ip: str\n"
            "    hostname: str = \"\"\n"
            "    state: str = \"unknown\"\n"
            "    os_guess: str = \"\"\n"
            "    os_accuracy: int = 0\n"
            "    services: list = field(default_factory=list)\n\n"
            "    @property\n"
            "    def open_port_count(self) -> int:\n"
            "        return sum(1 for s in self.services if s.state == \"open\")\n\n"
            "    @property\n"
            "    def risk_score(self) -> str:\n"
            "        \"\"\"Simple heuristic risk scoring.\"\"\"\n"
            "        risky_ports = {21, 22, 23, 25, 80, 443, 445, 1433, 3306, 3389, 5985, 5986}\n"
            "        risky_services = {s for s in self.services if s.port in risky_ports and s.state == \"open\"}\n"
            "        if len(risky_services) >= 5 or 3389 in {s.port for s in risky_services}:\n"
            "            return \"HIGH\"\n"
            "        elif len(risky_services) >= 2:\n"
            "            return \"MEDIUM\"\n"
            "        elif risky_services:\n"
            "            return \"LOW\"\n"
            "        return \"INFO\"\n\n\n"
            "def parse_nmap_xml(xml_path: str) -> list[Host]:\n"
            "    \"\"\"Parse Nmap XML and return list of Host objects.\"\"\"\n"
            "    tree = ET.parse(xml_path)\n"
            "    root = tree.getroot()\n"
            "    hosts = []\n\n"
            "    for host_elem in root.findall(\"host\"):\n"
            "        # IP address\n"
            "        addr_elem = host_elem.find(\".//address[@addrtype='ipv4']\")\n"
            "        if addr_elem is None:\n"
            "            continue\n"
            "        ip = addr_elem.get(\"addr\", \"\")\n\n"
            "        # Hostname\n"
            "        hostname_elem = host_elem.find(\".//hostname\")\n"
            "        hostname = hostname_elem.get(\"name\", \"\") if hostname_elem is not None else \"\"\n\n"
            "        # State\n"
            "        status_elem = host_elem.find(\"status\")\n"
            "        state = status_elem.get(\"state\", \"unknown\") if status_elem is not None else \"unknown\"\n\n"
            "        # OS detection\n"
            "        os_elem = host_elem.find(\".//osmatch\")\n"
            "        os_guess = os_elem.get(\"name\", \"\") if os_elem is not None else \"\"\n"
            "        os_acc = int(os_elem.get(\"accuracy\", 0)) if os_elem is not None else 0\n\n"
            "        # Services/ports\n"
            "        services = []\n"
            "        for port_elem in host_elem.findall(\".//port\"):\n"
            "            port_num = int(port_elem.get(\"portid\", 0))\n"
            "            protocol = port_elem.get(\"protocol\", \"tcp\")\n"
            "            state_elem = port_elem.find(\"state\")\n"
            "            port_state = state_elem.get(\"state\", \"\") if state_elem is not None else \"\"\n"
            "            svc_elem = port_elem.find(\"service\")\n"
            "            scripts = [\n"
            "                {\"id\": s.get(\"id\"), \"output\": s.get(\"output\", \"\")[:200]}\n"
            "                for s in port_elem.findall(\"script\")\n"
            "            ]\n"
            "            services.append(Service(\n"
            "                port=port_num, protocol=protocol, state=port_state,\n"
            "                name=svc_elem.get(\"name\", \"\") if svc_elem is not None else \"\",\n"
            "                product=svc_elem.get(\"product\", \"\") if svc_elem is not None else \"\",\n"
            "                version=svc_elem.get(\"version\", \"\") if svc_elem is not None else \"\",\n"
            "                scripts=scripts,\n"
            "            ))\n"
            "        hosts.append(Host(ip=ip, hostname=hostname, state=state,\n"
            "                         os_guess=os_guess, os_accuracy=os_acc, services=services))\n\n"
            "    return [h for h in hosts if h.state == \"up\"]\n\n\n"
            "def print_report(hosts: list[Host]):\n"
            "    \"\"\"Print a formatted pentest-ready report.\"\"\"\n"
            "    print(f\"\\n{'='*60}\")\n"
            "    print(f\"  NMAP SCAN REPORT — {len(hosts)} hosts up\")\n"
            "    print(f\"{'='*60}\\n\")\n"
            "    for host in sorted(hosts, key=lambda h: h.ip):\n"
            "        print(f\"[{host.risk_score}] {host.ip}  {host.hostname}\")\n"
            "        if host.os_guess:\n"
            "            print(f\"  OS: {host.os_guess} ({host.os_accuracy}% confidence)\")\n"
            "        open_svcs = [s for s in host.services if s.state == \"open\"]\n"
            "        for svc in open_svcs:\n"
            "            svc_str = f\"{svc.port}/{svc.protocol}  {svc.name}\"\n"
            "            if svc.product:\n"
            "                svc_str += f\"  [{svc.product} {svc.version}]\"\n"
            "            print(f\"  {svc_str}\")\n"
            "            for script in svc.scripts[:2]:\n"
            "                output_preview = script['output'].replace('\\n', ' ')[:100]\n"
            "                print(f\"    → {script['id']}: {output_preview}\")\n"
            "        print()\n\n\n"
            "def main():\n"
            "    parser = argparse.ArgumentParser(description=\"Nmap XML Parser — Hancock CyberViser\")\n"
            "    parser.add_argument(\"xml_file\", help=\"Nmap XML output file\")\n"
            "    parser.add_argument(\"--format\", choices=[\"text\", \"json\", \"csv\"], default=\"text\")\n"
            "    parser.add_argument(\"--output\", help=\"Output file (default: stdout)\")\n"
            "    args = parser.parse_args()\n\n"
            "    hosts = parse_nmap_xml(args.xml_file)\n"
            "    print(f\"Parsed {len(hosts)} live hosts.\", file=sys.stderr)\n\n"
            "    if args.format == \"text\":\n"
            "        print_report(hosts)\n"
            "    elif args.format == \"json\":\n"
            "        output = json.dumps([asdict(h) for h in hosts], indent=2)\n"
            "        if args.output:\n"
            "            Path(args.output).write_text(output)\n"
            "        else:\n"
            "            print(output)\n"
            "    elif args.format == \"csv\":\n"
            "        rows = []\n"
            "        for h in hosts:\n"
            "            for s in h.services:\n"
            "                if s.state == \"open\":\n"
            "                    rows.append({\"ip\": h.ip, \"hostname\": h.hostname, \"os\": h.os_guess,\n"
            "                                  \"port\": s.port, \"protocol\": s.protocol,\n"
            "                                  \"service\": s.name, \"product\": s.product,\n"
            "                                  \"version\": s.version, \"risk\": h.risk_score})\n"
            "        out = args.output or \"nmap_report.csv\"\n"
            "        with open(out, \"w\", newline=\"\") as f:\n"
            "            writer = csv.DictWriter(f, fieldnames=rows[0].keys())\n"
            "            writer.writeheader(); writer.writerows(rows)\n"
            "        print(f\"CSV saved → {out}\")\n\n\n"
            "if __name__ == \"__main__\":\n"
            "    main()\n"
            "```"
        ),
    },
    {
        "category": "siem_queries",
        "user": "Write Splunk SPL queries to detect common attack patterns: failed logins, lateral movement, data exfiltration.",
        "assistant": (
            "# Splunk SPL Hunting Queries — Hancock CyberViser\n\n"
            "## 1. Brute Force / Password Spray Detection\n"
            "```spl\n"
            "index=wineventlog EventCode=4625\n"
            "| bucket span=10m _time\n"
            "| stats count as failures dc(Account_Name) as unique_accounts by _time, src_ip\n"
            "| where failures > 20 AND unique_accounts > 5\n"
            "| eval attack_type=if(unique_accounts > 10, \"password_spray\", \"brute_force\")\n"
            "| sort -failures\n"
            "| table _time, src_ip, failures, unique_accounts, attack_type\n"
            "```\n\n"
            "## 2. Lateral Movement — Pass-the-Hash / PsExec\n"
            "```spl\n"
            "index=wineventlog EventCode=4624 Logon_Type=3\n"
            "| stats dc(host) as unique_dest values(host) as destinations count by Account_Name src_ip\n"
            "| where unique_dest > 3\n"
            "| eval risk=if(unique_dest > 10, \"HIGH\", \"MEDIUM\")\n"
            "| sort -unique_dest\n"
            "| table Account_Name, src_ip, unique_dest, destinations, risk\n"
            "```\n\n"
            "## 3. Data Exfiltration — Large Outbound Transfers\n"
            "```spl\n"
            "index=network src_zone=internal dest_zone=external\n"
            "| bucket span=1h _time\n"
            "| stats sum(bytes_out) as total_bytes_out by _time, src_ip, dest_ip\n"
            "| where total_bytes_out > 104857600  | 100MB threshold\n"
            "| eval total_mb=round(total_bytes_out/1048576, 2)\n"
            "| lookup threat_intel_ips ip as dest_ip OUTPUT verdict as ti_verdict\n"
            "| eval risk=if(isnotnull(ti_verdict), \"CRITICAL: Known Bad IP\", \"HIGH: Large Upload\")\n"
            "| sort -total_bytes_out\n"
            "| table _time, src_ip, dest_ip, total_mb, risk\n"
            "```\n\n"
            "## 4. PowerShell Suspicious Activity\n"
            "```spl\n"
            "index=wineventlog source=\"WinEventLog:Microsoft-Windows-PowerShell/Operational\"\n"
            "EventCode=4104\n"
            "| search ScriptBlockText IN (\"*IEX*\", \"*Invoke-Expression*\", \"*-EncodedCommand*\",\n"
            "                             \"*DownloadString*\", \"*WebClient*\", \"*bypass*\")\n"
            "| eval risk=case(\n"
            "    like(ScriptBlockText, \"%mimikatz%\"), \"CRITICAL\",\n"
            "    like(ScriptBlockText, \"%IEX*Download%\"), \"HIGH\",\n"
            "    like(ScriptBlockText, \"%-EncodedCommand%\"), \"MEDIUM\",\n"
            "    true(), \"LOW\")\n"
            "| table _time, ComputerName, UserID, risk, ScriptBlockText\n"
            "| sort -risk\n"
            "```\n\n"
            "## 5. New Local Admin Account Created\n"
            "```spl\n"
            "index=wineventlog EventCode=4732\n"
            "| search Group_Name=\"Administrators\"\n"
            "| eval alert=\"New local admin: \" + Member_Name + \" added to Administrators by \" + Account_Name\n"
            "| table _time, ComputerName, Member_Name, Account_Name, alert\n"
            "```\n\n"
            "## 6. DNS Exfiltration / Tunneling\n"
            "```spl\n"
            "index=dns\n"
            "| eval query_length=len(query)\n"
            "| stats count avg(query_length) as avg_len dc(query) as unique_queries by src_ip\n"
            "| where avg_len > 50 AND unique_queries > 100\n"
            "| eval risk=\"Possible DNS tunneling\"\n"
            "| table src_ip, count, avg_len, unique_queries, risk\n"
            "```\n\n"
            "## 7. Rare Process on Sensitive Hosts\n"
            "```spl\n"
            "index=wineventlog EventCode=4688 host IN (domain_controllers, file_servers)\n"
            "| stats count by New_Process_Name\n"
            "| where count < 3\n"
            "| eval alert=\"Rare process on sensitive host: \" + New_Process_Name\n"
            "| sort -count\n"
            "```"
        ),
    },
    {
        "category": "pentest_tools",
        "user": "Write a Python port scanner that uses threading for speed.",
        "assistant": (
            "⚠️ **Authorization Warning:** Only use this tool on systems you own or have explicit written permission to test. Unauthorized port scanning may be illegal.\n\n"
            "```python\n"
            "#!/usr/bin/env python3\n"
            "\"\"\"\n"
            "Fast Threaded Port Scanner — Hancock CyberViser\n"
            "For authorized penetration testing only.\n"
            "\n"
            "Usage:\n"
            "    python port_scanner.py -t 192.168.1.1 -p 1-1024\n"
            "    python port_scanner.py -t 192.168.1.0/24 -p 22,80,443,3389 --threads 200\n"
            "\"\"\"\n"
            "import argparse\n"
            "import ipaddress\n"
            "import socket\n"
            "import sys\n"
            "from concurrent.futures import ThreadPoolExecutor, as_completed\n"
            "from dataclasses import dataclass\n"
            "from typing import Optional\n\n\n"
            "COMMON_PORTS = [\n"
            "    21, 22, 23, 25, 53, 80, 110, 111, 135, 139, 143, 443, 445,\n"
            "    993, 995, 1723, 3306, 3389, 5900, 8080, 8443, 8888\n"
            "]\n\n\n"
            "@dataclass\n"
            "class PortResult:\n"
            "    host: str\n"
            "    port: int\n"
            "    state: str  # open / closed / filtered\n"
            "    banner: str = \"\"\n\n\n"
            "def scan_port(host: str, port: int, timeout: float = 1.0, grab_banner: bool = True) -> PortResult:\n"
            "    \"\"\"Scan a single port on a host.\"\"\"\n"
            "    try:\n"
            "        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:\n"
            "            sock.settimeout(timeout)\n"
            "            result = sock.connect_ex((host, port))\n"
            "            if result == 0:\n"
            "                banner = \"\"\n"
            "                if grab_banner:\n"
            "                    try:\n"
            "                        sock.settimeout(2.0)\n"
            "                        # Send HTTP HEAD for web ports\n"
            "                        if port in (80, 8080, 8000):\n"
            "                            sock.send(b\"HEAD / HTTP/1.0\\r\\n\\r\\n\")\n"
            "                        banner = sock.recv(1024).decode(\"utf-8\", errors=\"replace\").split(\"\\n\")[0][:100]\n"
            "                    except Exception:\n"
            "                        pass\n"
            "                return PortResult(host, port, \"open\", banner)\n"
            "            return PortResult(host, port, \"closed\")\n"
            "    except socket.timeout:\n"
            "        return PortResult(host, port, \"filtered\")\n"
            "    except OSError:\n"
            "        return PortResult(host, port, \"error\")\n\n\n"
            "def parse_ports(port_spec: str) -> list[int]:\n"
            "    \"\"\"Parse port spec: '80', '1-1024', '22,80,443', or 'common'.\"\"\"\n"
            "    if port_spec == \"common\":\n"
            "        return COMMON_PORTS\n"
            "    ports: set[int] = set()\n"
            "    for part in port_spec.split(\",\"):\n"
            "        if \"-\" in part:\n"
            "            start, end = part.split(\"-\", 1)\n"
            "            ports.update(range(int(start), int(end) + 1))\n"
            "        else:\n"
            "            ports.add(int(part))\n"
            "    return sorted(ports)\n\n\n"
            "def scan_host(host: str, ports: list[int], threads: int = 100,\n"
            "               timeout: float = 1.0) -> list[PortResult]:\n"
            "    \"\"\"Scan all specified ports on a host using thread pool.\"\"\"\n"
            "    results = []\n"
            "    with ThreadPoolExecutor(max_workers=threads) as executor:\n"
            "        futures = {executor.submit(scan_port, host, port, timeout): port\n"
            "                   for port in ports}\n"
            "        for future in as_completed(futures):\n"
            "            result = future.result()\n"
            "            if result.state == \"open\":\n"
            "                results.append(result)\n"
            "    return sorted(results, key=lambda r: r.port)\n\n\n"
            "def main():\n"
            "    parser = argparse.ArgumentParser(\n"
            "        description=\"Port Scanner — Hancock CyberViser (authorized use only)\")\n"
            "    parser.add_argument(\"-t\", \"--target\", required=True,\n"
            "                        help=\"Target host, IP, or CIDR range\")\n"
            "    parser.add_argument(\"-p\", \"--ports\", default=\"common\",\n"
            "                        help=\"Ports: '80', '1-1024', '22,443', or 'common'\")\n"
            "    parser.add_argument(\"--threads\", type=int, default=100)\n"
            "    parser.add_argument(\"--timeout\", type=float, default=1.0)\n"
            "    args = parser.parse_args()\n\n"
            "    ports = parse_ports(args.ports)\n"
            "    print(f\"[*] Scanning {args.target} — {len(ports)} ports, {args.threads} threads\")\n\n"
            "    # Handle CIDR or single host\n"
            "    try:\n"
            "        network = ipaddress.ip_network(args.target, strict=False)\n"
            "        hosts = [str(ip) for ip in network.hosts()]\n"
            "    except ValueError:\n"
            "        hosts = [args.target]\n\n"
            "    for host in hosts:\n"
            "        open_ports = scan_host(host, ports, args.threads, args.timeout)\n"
            "        if open_ports:\n"
            "            print(f\"\\n[+] {host} — {len(open_ports)} open ports\")\n"
            "            for result in open_ports:\n"
            "                banner_str = f\"  [{result.banner}]\" if result.banner else \"\"\n"
            "                print(f\"  {result.port}/tcp  OPEN{banner_str}\")\n\n\n"
            "if __name__ == \"__main__\":\n"
            "    main()\n"
            "```"
        ),
    },
    {
        "category": "secure_code_review",
        "user": "Review this Python Flask code for security vulnerabilities:\n\n```python\nfrom flask import Flask, request\nimport subprocess\nimport sqlite3\n\napp = Flask(__name__)\n\n@app.route('/exec')\ndef execute():\n    cmd = request.args.get('cmd')\n    result = subprocess.run(cmd, shell=True, capture_output=True)\n    return result.stdout\n\n@app.route('/user')\ndef get_user():\n    uid = request.args.get('id')\n    conn = sqlite3.connect('users.db')\n    cursor = conn.cursor()\n    cursor.execute(f\"SELECT * FROM users WHERE id = {uid}\")\n    return cursor.fetchone()\n```",
        "assistant": (
            "## Security Code Review — Critical Vulnerabilities Found\n\n"
            "### 🔴 CRITICAL: OS Command Injection (CWE-78)\n"
            "**Location:** `/exec` endpoint, line: `subprocess.run(cmd, shell=True, ...)`\n\n"
            "**Issue:** `cmd` is taken directly from `request.args` (user-controlled) and passed to "
            "`subprocess.run` with `shell=True`. This allows arbitrary OS command execution:\n"
            "```\n"
            "GET /exec?cmd=ls%3Bcat%20/etc/passwd%3Bwhoami\n"
            "# Executes: ls; cat /etc/passwd; whoami\n"
            "```\n\n"
            "**Fix:**\n"
            "```python\n"
            "# Option 1: Remove the endpoint entirely (preferred)\n"
            "# Option 2: If OS commands are required, use a strict whitelist\n"
            "import shlex\n\n"
            "ALLOWED_COMMANDS = {\"date\", \"uptime\", \"hostname\"}  # strict allowlist\n\n"
            "@app.route('/exec')\n"
            "def execute():\n"
            "    cmd = request.args.get('cmd', '')\n"
            "    if cmd not in ALLOWED_COMMANDS:\n"
            "        return 'Unauthorized command', 403\n"
            "    # Never use shell=True with user input\n"
            "    result = subprocess.run([cmd], shell=False, capture_output=True, text=True, timeout=10)\n"
            "    return result.stdout\n"
            "```\n\n"
            "### 🔴 CRITICAL: SQL Injection (CWE-89)\n"
            "**Location:** `/user` endpoint, line: `cursor.execute(f\"SELECT * FROM users WHERE id = {uid}\")`\n\n"
            "**Issue:** `uid` is user-controlled and directly interpolated into the SQL query. "
            "Attacker can extract the entire database or drop tables:\n"
            "```\n"
            "GET /user?id=1 UNION SELECT username,password,3,4 FROM users--\n"
            "GET /user?id=1; DROP TABLE users--\n"
            "```\n\n"
            "**Fix:** Use parameterized queries (never string interpolation):\n"
            "```python\n"
            "@app.route('/user')\n"
            "def get_user():\n"
            "    uid = request.args.get('id', '')\n"
            "    # Validate: only allow integer IDs\n"
            "    if not uid.isdigit():\n"
            "        return 'Invalid ID', 400\n"
            "    conn = sqlite3.connect('users.db')\n"
            "    cursor = conn.cursor()\n"
            "    # ✅ Parameterized query — SQL injection impossible\n"
            "    cursor.execute(\"SELECT id, username, email FROM users WHERE id = ?\", (int(uid),))\n"
            "    row = cursor.fetchone()\n"
            "    conn.close()\n"
            "    if not row:\n"
            "        return 'User not found', 404\n"
            "    return {'id': row[0], 'username': row[1], 'email': row[2]}\n"
            "```\n\n"
            "### 🟡 HIGH: Missing Authentication\n"
            "Neither endpoint has authentication. The `/exec` command injection becomes internet-accessible "
            "if this service is exposed.\n"
            "```python\n"
            "from functools import wraps\n"
            "from flask import request\n\n"
            "def require_api_key(f):\n"
            "    @wraps(f)\n"
            "    def decorated(*args, **kwargs):\n"
            "        key = request.headers.get('X-API-Key')\n"
            "        if key != os.environ.get('API_KEY'):\n"
            "            return 'Unauthorized', 401\n"
            "        return f(*args, **kwargs)\n"
            "    return decorated\n"
            "```\n\n"
            "### 🟡 MEDIUM: Sensitive Data Exposure\n"
            "`SELECT *` returns all columns including potentially hashed passwords. "
            "Always select only required columns.\n\n"
            "### Summary\n"
            "| Severity | Issue | CWE | CVSS |\n"
            "|----------|-------|-----|------|\n"
            "| 🔴 Critical | OS Command Injection | CWE-78 | 9.8 |\n"
            "| 🔴 Critical | SQL Injection | CWE-89 | 9.8 |\n"
            "| 🟡 High | Missing Authentication | CWE-306 | 8.6 |\n"
            "| 🟡 Medium | Sensitive Data Exposure | CWE-200 | 6.5 |"
        ),
    },
    {
        "category": "bash_scripting",
        "user": "Write a Bash script to automate Linux privilege escalation enumeration (like LinPEAS but simpler).",
        "assistant": (
            "⚠️ **Authorization Warning:** Only use on systems you own or have explicit permission to test.\n\n"
            "```bash\n"
            "#!/usr/bin/env bash\n"
            "# linux_enum.sh — Linux Privilege Escalation Enumerator\n"
            "# Hancock / CyberViser — Authorized use only\n"
            "# Usage: bash linux_enum.sh 2>/dev/null | tee enum_output.txt\n\n"
            "RED='\\033[0;31m'; YLW='\\033[0;33m'; GRN='\\033[0;32m'; NC='\\033[0m'\n"
            "section() { echo -e \"\\n${YLW}[+] $1${NC}\"; echo '─────────────────────────────────────'; }\n"
            "hit()     { echo -e \"  ${RED}[!] $1${NC}\"; }\n"
            "info()    { echo -e \"  ${GRN}[*] $1${NC}\"; }\n\n"
            "echo -e \"${RED}=== Linux Privilege Escalation Enumeration ===${NC}\"\n"
            "echo \"  User: $(whoami) | Host: $(hostname) | Date: $(date)\"\n\n"
            "# ── System Information ──────────────────────────────────────────\n"
            "section \"System Information\"\n"
            "uname -a\n"
            "cat /etc/os-release 2>/dev/null | head -5\n"
            "lscpu | grep 'Model name' 2>/dev/null\n\n"
            "# ── Current User Context ─────────────────────────────────────────\n"
            "section \"User & Privileges\"\n"
            "id\n"
            "echo \"Groups: $(groups)\"\n"
            "echo \"Home: $HOME\"\n"
            "[[ $(id -u) -eq 0 ]] && hit \"RUNNING AS ROOT!\"\n\n"
            "# ── Sudo Permissions ─────────────────────────────────────────────\n"
            "section \"Sudo Permissions\"\n"
            "sudo -l 2>/dev/null && hit \"Sudo entries found — check GTFOBins!\"\n\n"
            "# ── SUID Binaries ─────────────────────────────────────────────────\n"
            "section \"SUID Binaries\"\n"
            "find / -perm -4000 -type f 2>/dev/null | while read f; do\n"
            "    hit \"SUID: $f\"\n"
            "done\n\n"
            "# ── SGID Binaries ─────────────────────────────────────────────────\n"
            "section \"SGID Binaries\"\n"
            "find / -perm -2000 -type f 2>/dev/null | while read f; do\n"
            "    info \"SGID: $f\"\n"
            "done\n\n"
            "# ── World-Writable Files ──────────────────────────────────────────\n"
            "section \"World-Writable Sensitive Files\"\n"
            "for f in /etc/passwd /etc/shadow /etc/sudoers /etc/crontab; do\n"
            "    [[ -w \"$f\" ]] && hit \"Writable: $f\"\n"
            "done\n\n"
            "# ── Cron Jobs ────────────────────────────────────────────────────\n"
            "section \"Cron Jobs\"\n"
            "cat /etc/crontab 2>/dev/null\n"
            "ls -la /etc/cron.* 2>/dev/null\n"
            "crontab -l 2>/dev/null\n"
            "# Look for writable scripts called by cron\n"
            "grep -r '\\*.*/' /etc/cron* /var/spool/cron 2>/dev/null | grep -v '^#' | while read line; do\n"
            "    script=$(echo \"$line\" | awk '{print $NF}')\n"
            "    [[ -w \"$script\" ]] && hit \"Writable cron script: $script\"\n"
            "done\n\n"
            "# ── Capabilities ─────────────────────────────────────────────────\n"
            "section \"Linux Capabilities\"\n"
            "getcap -r / 2>/dev/null | while read line; do\n"
            "    hit \"Capability: $line\"\n"
            "done\n\n"
            "# ── Services & Network ───────────────────────────────────────────\n"
            "section \"Listening Services\"\n"
            "ss -tlnp 2>/dev/null || netstat -tlnp 2>/dev/null\n\n"
            "# ── Environment Variables ────────────────────────────────────────\n"
            "section \"Interesting Environment Variables\"\n"
            "env | grep -iE 'pass|key|secret|token|api|cred' 2>/dev/null | while read e; do\n"
            "    hit \"Env cred: $e\"\n"
            "done\n\n"
            "# ── Config Files with Credentials ───────────────────────────────\n"
            "section \"Config Files (Potential Credentials)\"\n"
            "for pattern in password passwd api_key secret token; do\n"
            "    grep -r \"$pattern\" /home /etc /var/www 2>/dev/null --include='*.conf' \\\n"
            "        --include='*.yml' --include='*.env' --include='*.ini' -l | while read f; do\n"
            "        hit \"Possible creds in: $f\"\n"
            "    done\n"
            "done\n\n"
            "echo -e \"\\n${GRN}[*] Enumeration complete. Cross-reference findings with GTFOBins.${NC}\"\n"
            "echo \"    https://gtfobins.github.io/\"\n"
            "```"
        ),
    },
]


def generate():
    samples = []
    for item in KB:
        samples.append({
            "messages": [
                {"role": "system",    "content": HANCOCK_SYSTEM},
                {"role": "user",      "content": item["user"]},
                {"role": "assistant", "content": item["assistant"]},
            ]
        })
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        json.dump(samples, f, indent=2)
    print(f"[code_kb] ✅ {len(samples)} samples → {OUTPUT_FILE}")
    return samples


if __name__ == "__main__":
    generate()
