"""
IOC Threat Intelligence Knowledge Base — Hancock CyberViser
Q&A pairs for IOC enrichment and threat intelligence analysis.
Outputs: data/raw_ioc_kb.json
"""
import json
from pathlib import Path

OUTPUT_FILE = Path(__file__).parent.parent / "data" / "raw_ioc_kb.json"

HANCOCK_SYSTEM = (
    "You are Hancock IOC, CyberViser's threat intelligence analyst. "
    "When given an indicator of compromise (IP address, domain, URL, file hash, or email), "
    "you provide a structured enrichment report covering: indicator type and classification, "
    "threat intelligence context (known malware families, threat actors, campaigns), "
    "MITRE ATT&CK techniques, risk score (1-10) with justification, "
    "recommended defensive actions, and relevant CVEs if applicable. "
    "Format your response as a clear, structured threat intel report."
)

KB = [
    # ── IP ADDRESS IOCS ───────────────────────────────────────────────────────────
    {
        "category": "ip_ioc",
        "user": "Analyze this suspicious IP: 185.220.101.45 — it appeared in our firewall logs making repeated connection attempts on port 443.",
        "assistant": (
            "# Threat Intelligence Report — IP: 185.220.101.45\n\n"
            "## Indicator Classification\n"
            "**Type:** IPv4 Address\n"
            "**Category:** Tor Exit Node / Scanning Infrastructure\n"
            "**Risk Score: 7/10**\n\n"
            "## Threat Intelligence Context\n"
            "IP 185.220.101.45 is a well-documented **Tor exit node** (confirmed in multiple public threat intel feeds). "
            "Tor exit nodes are routinely used by:\n"
            "- Threat actors for anonymous C2 communications\n"
            "- Ransomware operators during initial access phase\n"
            "- Credential stuffing and brute-force campaigns\n"
            "- ProxyBot/SOCKS5 relay networks\n\n"
            "Historically associated with: **Cobalt Strike beacon callbacks**, **REvil/Sodinokibi** infrastructure, "
            "and general scanning activity.\n\n"
            "## MITRE ATT&CK Mapping\n"
            "| Technique | ID | Description |\n"
            "|-----------|-----|-------------|\n"
            "| Proxy: Multi-hop Proxy | T1090.003 | Tor exit node anonymization |\n"
            "| Reconnaissance: Network Scanning | T1595 | Port 443 scanning activity |\n"
            "| Command and Control | T1071.001 | HTTPS-based C2 via Tor |\n\n"
            "## Verification Steps\n"
            "```bash\n"
            "# Check Tor exit node status:\n"
            "curl https://check.torproject.org/cgi-bin/TorBulkExitList.py | grep 185.220.101.45\n\n"
            "# Enrich with multiple sources:\n"
            "# VirusTotal: https://www.virustotal.com/gui/ip-address/185.220.101.45\n"
            "# Shodan: https://www.shodan.io/host/185.220.101.45\n"
            "# AbuseIPDB: https://www.abuseipdb.com/check/185.220.101.45\n"
            "# AlienVault OTX: https://otx.alienvault.com/indicator/ip/185.220.101.45\n"
            "```\n\n"
            "## Recommended Actions\n"
            "1. **Block** — Add to firewall deny list; Tor exits rarely have legitimate business use\n"
            "2. **Investigate** — Review all connections from this IP in the last 30 days:\n"
            "   ```spl\n"
            "   index=firewall src_ip=185.220.101.45 | table _time, dest_ip, dest_port, bytes_in, bytes_out\n"
            "   ```\n"
            "3. **Check for beaconing** — Regular intervals to this IP may indicate active C2\n"
            "4. **Threat hunt** — Identify any hosts that initiated connections *to* this IP\n\n"
            "## Disposition\n"
            "**BLOCK** — High confidence malicious infrastructure. No legitimate business justification for Tor exit node traffic."
        ),
    },
    {
        "category": "ip_ioc",
        "user": "How do I enrich an IP address IOC? What tools and process should I use?",
        "assistant": (
            "# IOC Enrichment Process — IP Address\n\n"
            "## Step 1: Classify the IP\n"
            "Before enriching, determine context:\n"
            "- Is it external (public) or internal (RFC 1918)?\n"
            "- Is it a source (attacker) or destination (C2/exfil)?\n"
            "- What protocol/port was involved?\n\n"
            "## Step 2: Automated Enrichment (Priority Order)\n\n"
            "**Free Tier Sources:**\n"
            "| Tool | What it provides | API? |\n"
            "|------|------------------|------|\n"
            "| VirusTotal | AV vendor detections, community scores | Yes (free) |\n"
            "| Shodan | Open ports, banner data, ASN, CVEs | Yes (free limited) |\n"
            "| AbuseIPDB | Abuse reports, categories, confidence | Yes (free) |\n"
            "| AlienVault OTX | Threat intel pulses, malware families | Yes (free) |\n"
            "| GreyNoise | Mass internet scanners, Tor nodes | Yes (free tier) |\n"
            "| IPVoid | Multi-source blacklist check | Web only |\n\n"
            "**Paid/Enterprise:**\n"
            "- Recorded Future, Mandiant Advantage, ThreatConnect, MISP\n\n"
            "## Step 3: OSINT Checks\n"
            "```bash\n"
            "# Reverse DNS\n"
            "dig -x <IP>\n"
            "host <IP>\n\n"
            "# ASN/Org lookup\n"
            "whois <IP> | grep -i 'asn\\|org\\|netname'\n"
            "curl https://ipinfo.io/<IP>\n\n"
            "# Shodan CLI\n"
            "shodan host <IP>\n\n"
            "# GreyNoise — is it a mass scanner?\n"
            "curl 'https://api.greynoise.io/v3/community/<IP>'\n"
            "```\n\n"
            "## Step 4: Context from Your Environment\n"
            "```spl\n"
            "# Splunk: All activity involving this IP (last 30 days)\n"
            "index=* (src_ip=<IP> OR dest_ip=<IP>)\n"
            "| stats count by index, sourcetype, src_ip, dest_ip, dest_port\n"
            "| sort -count\n"
            "```\n\n"
            "## Step 5: Scoring & Disposition\n"
            "| Score | Criteria | Action |\n"
            "|-------|----------|--------|\n"
            "| 9–10 | Known C2, malware, active TI alerts | Block + Escalate |\n"
            "| 7–8 | Multiple TI detections, Tor, VPN abuse | Block |\n"
            "| 5–6 | Scanning infrastructure, some TI hits | Monitor + Alert |\n"
            "| 1–4 | Few detections, CDN, legitimate infra | Investigate further |\n\n"
            "## Automation\n"
            "```python\n"
            "# Quick multi-source enrichment script\n"
            "import requests\n\n"
            "def enrich_ip(ip: str):\n"
            "    vt = requests.get(f'https://www.virustotal.com/api/v3/ip_addresses/{ip}',\n"
            "                      headers={'x-apikey': 'YOUR_VT_KEY'}).json()\n"
            "    malicious = vt['data']['attributes']['last_analysis_stats']['malicious']\n"
            "    print(f'VT malicious detections: {malicious}/90')\n"
            "```"
        ),
    },
    # ── DOMAIN IOCS ──────────────────────────────────────────────────────────────
    {
        "category": "domain_ioc",
        "user": "I have a suspicious domain: update-microsoft-security.com — it appeared in DNS logs. How do I analyze it?",
        "assistant": (
            "# Threat Intelligence Report — Domain: update-microsoft-security.com\n\n"
            "## Indicator Classification\n"
            "**Type:** Domain Name\n"
            "**Category:** Typosquatting / Phishing / Potential C2\n"
            "**Risk Score: 8/10**\n\n"
            "## Initial Assessment\n"
            "This domain exhibits **classic malicious domain characteristics:**\n"
            "- **Typosquatting:** impersonates Microsoft using 'microsoft-security' pattern\n"
            "- **Newly registered** (check below) — malicious domains are often <30 days old\n"
            "- **Suspicious TLD usage:** `.com` for impersonation (legitimate Microsoft uses `microsoft.com`)\n"
            "- **Compound keywords:** combining 'update' + 'microsoft' + 'security' = social engineering pattern\n\n"
            "## Enrichment Steps\n"
            "```bash\n"
            "# Registration date (newly registered = higher risk)\n"
            "whois update-microsoft-security.com | grep -i 'creat\\|registr'\n\n"
            "# DNS resolution\n"
            "dig +short update-microsoft-security.com A\n"
            "dig +short update-microsoft-security.com MX\n"
            "dig +short update-microsoft-security.com TXT\n\n"
            "# Certificate transparency logs (subdomains, related certs)\n"
            "curl 'https://crt.sh/?q=update-microsoft-security.com&output=json'\n\n"
            "# Passive DNS (historical resolutions)\n"
            "# → VirusTotal: https://www.virustotal.com/gui/domain/update-microsoft-security.com\n"
            "# → SecurityTrails: https://securitytrails.com/domain/update-microsoft-security.com/dns\n"
            "# → RiskIQ: https://community.riskiq.com\n\n"
            "# URL scan (if URL is known)\n"
            "curl 'https://urlscan.io/api/v1/scan/' -d '{\"url\":\"http://update-microsoft-security.com\"}'\n"
            "```\n\n"
            "## MITRE ATT&CK Mapping\n"
            "| Technique | ID |\n"
            "|-----------|-----|\n"
            "| Phishing | T1566 |\n"
            "| Domain Generation Algorithm / C2 | T1568 |\n"
            "| Masquerading | T1036 |\n\n"
            "## Recommended Actions\n"
            "1. **Block at DNS resolver** (Pi-hole, Bluecoat, Cisco Umbrella, Windows DNS RPZ)\n"
            "2. **Block at proxy/web filter** — add to URL category 'malicious'\n"
            "3. **Investigate DNS logs** for which internal hosts resolved this domain:\n"
            "   ```spl\n"
            "   index=dns query=update-microsoft-security.com | stats count by src_ip, _time\n"
            "   ```\n"
            "4. **Identify affected hosts** — any host that resolved it may have received a phishing email\n"
            "5. **Check email gateway** — search for emails containing this domain\n\n"
            "## Disposition\n"
            "**BLOCK + INVESTIGATE** — Highly suspicious impersonation domain. "
            "Treat any host that resolved this as potentially compromised until proven otherwise."
        ),
    },
    {
        "category": "domain_ioc",
        "user": "What are DGA domains and how do I detect them in my environment?",
        "assistant": (
            "# Domain Generation Algorithm (DGA) Detection Guide\n\n"
            "## What are DGA Domains?\n"
            "Malware generates domain names algorithmically (using a seed like date/time) to create "
            "thousands of potential C2 domains. The attacker registers just a few — the malware tries "
            "all of them until one resolves. This evades static domain blocklists.\n\n"
            "**Common DGA malware families:**\n"
            "- Cryptolocker, Conficker, Ramnit, GameOver Zeus\n"
            "- Dridex, Emotet (hybrid DGA), Suppobox\n"
            "- Bumblebee, Qakbot (modern examples)\n\n"
            "## DGA Domain Characteristics\n"
            "| Indicator | Example | Legitimate |\n"
            "|-----------|---------|------------|\n"
            "| Random-looking string | `xkqpvntlhj.com` | `google.com` |\n"
            "| High consonant ratio | `bxvzqkplm.net` | readable words |\n"
            "| Short registration age | 1–7 days | years |\n"
            "| NXDOMAIN responses | 95%+ fail | rare failure |\n"
            "| No matching MX/TXT | DNS-only | usually has MX |\n"
            "| Low Alexa/Tranco rank | not ranked | top 1M |\n\n"
            "## Detection in Splunk\n"
            "```spl\n"
            "index=dns message_type=QUERY\n"
            "| eval domain_len=len(query)\n"
            "| eval digits=len(replace(query, \"[^0-9]\", \"\"))\n"
            "| eval consonants=len(replace(lower(query), \"[^bcdfghjklmnpqrstvwxyz.\\\\-]\", \"\"))\n"
            "| eval vowels=len(replace(lower(query), \"[^aeiou]\", \"\"))\n"
            "| eval consonant_ratio=if(vowels>0, consonants/vowels, 99)\n"
            "| where domain_len > 15 AND consonant_ratio > 3.5 AND NOT query==\"*microsoft*\"\n"
            "| stats count dc(query) as unique_domains by src_ip\n"
            "| where unique_domains > 10\n"
            "| sort -unique_domains\n"
            "```\n\n"
            "## Detection in Elastic/KQL\n"
            "```kql\n"
            "dns.question.type: A AND\n"
            "NOT dns.resolved_ip: * AND   // NXDOMAIN\n"
            "dns.question.name: *\n"
            "// Filter by entropy using scripted field or ML\n"
            "```\n\n"
            "## Automated DGA Classifiers\n"
            "- **Cisco Umbrella** — built-in DGA detection\n"
            "- **MISP DGA feeds** — feeds with known DGA domains\n"
            "- **DGA Detective (open-source)** — ML model for DGA classification\n"
            "- **Virustotal domains** — 'malicious' + 'DGA' category\n\n"
            "## Response\n"
            "1. Identify hosts with high NXDOMAIN rates (>50 unique NXDOMAIN in 1 hour)\n"
            "2. Extract domain list from host via memory forensics or network capture\n"
            "3. Identify DGA family using DGA Detective or `dga-predict` Python library\n"
            "4. Block the IP resolved by the working DGA domain at firewall level\n"
            "5. Isolate infected host, run EDR full scan, collect memory image"
        ),
    },
    # ── HASH IOCS ──────────────────────────────────────────────────────────────────
    {
        "category": "hash_ioc",
        "user": "I have a suspicious file hash: SHA256 3395856ce81f2b7382dee72602f798b642f14140. How do I analyze it?",
        "assistant": (
            "# Threat Intelligence Report — File Hash\n\n"
            "## Indicator Classification\n"
            "**Type:** File Hash (appears to be SHA1 — 40 hex chars)\n"
            "**Note:** The hash `3395856ce81f2b7382dee72602f798b642f14140` is a **well-known test hash** "
            "(EICAR test file signature). It is used to verify AV detection. "
            "Replace with your actual hash for real analysis.\n\n"
            "## Hash Enrichment Process\n\n"
            "**Step 1: VirusTotal Lookup**\n"
            "```bash\n"
            "# API lookup\n"
            "curl 'https://www.virustotal.com/api/v3/files/<SHA256>' \\\n"
            "  -H 'x-apikey: YOUR_VT_KEY' | python3 -m json.tool\n\n"
            "# Key fields to check:\n"
            "# .data.attributes.last_analysis_stats.malicious  → detection count\n"
            "# .data.attributes.names                         → known filenames\n"
            "# .data.attributes.magic                         → file type\n"
            "# .data.attributes.tags                          → 'peexe', 'upx', 'signed'\n"
            "# .data.attributes.signature_info                → code signing\n"
            "```\n\n"
            "**Step 2: Multi-Source Enrichment**\n"
            "```bash\n"
            "# MalwareBazaar (free)\n"
            "curl 'https://mb-api.abuse.ch/api/v1/' \\\n"
            "  -d 'query=get_info&hash=<SHA256>'\n\n"
            "# Hybrid Analysis (free sandbox)\n"
            "curl 'https://www.hybrid-analysis.com/api/v2/search/hash' \\\n"
            "  -H 'api-key: YOUR_KEY' \\\n"
            "  -d 'hash=<SHA256>'\n\n"
            "# ANY.RUN (interactive sandbox)\n"
            "# Upload via: https://app.any.run/\n"
            "```\n\n"
            "**Step 3: OSINT Context**\n"
            "Check for:\n"
            "- Known malware family name (AV detections)\n"
            "- Associated C2 infrastructure (from sandbox reports)\n"
            "- File name(s) used in the wild\n"
            "- First/last seen dates\n"
            "- MITRE ATT&CK mapping (from sandbox behavior)\n\n"
            "**Step 4: PE Analysis (if EXE/DLL)**\n"
            "```bash\n"
            "# PEStudio / pestool\n"
            "pestool --all malware.exe\n\n"
            "# Static analysis with FLOSS (string extraction)\n"
            "floss malware.exe --no-progress\n\n"
            "# Import hash (imphash) — fingerprints compiler/linker\n"
            "python3 -c \"import pefile; p=pefile.PE('malware.exe'); print(p.get_imphash())\"\n"
            "```\n\n"
            "## Disposition Matrix\n"
            "| VT Detections | Action |\n"
            "|---------------|--------|\n"
            "| 50+/72 | Confirmed malware — block hash, isolate host, escalate |\n"
            "| 20–49 | High confidence — block + investigate |\n"
            "| 5–19 | Suspicious — sandbox detonate + investigate |\n"
            "| 1–4 | Inconclusive — sandbox detonate + context analysis |\n"
            "| 0 (first seen <7 days) | Zero-day risk — sandbox + behavioral analysis |\n"
            "| 0 (old, signed) | Likely benign — verify signature and context |"
        ),
    },
    {
        "category": "hash_ioc",
        "user": "What's the difference between MD5, SHA1, SHA256, and fuzzy hashes like ssdeep for malware analysis?",
        "assistant": (
            "# Hash Types in Malware Analysis — Complete Reference\n\n"
            "## Cryptographic Hashes (Exact Match)\n\n"
            "| Hash | Length | Speed | Collision Resistant | Common Use |\n"
            "|------|--------|-------|---------------------|------------|\n"
            "| **MD5** | 32 hex (128-bit) | Fastest | ❌ Broken | Legacy TI feeds, quick lookup |\n"
            "| **SHA1** | 40 hex (160-bit) | Fast | ❌ Theoretical breaks | Older TI databases, YARA |\n"
            "| **SHA256** | 64 hex (256-bit) | Moderate | ✅ Strong | Gold standard: VT, MalwareBazaar, EDR |\n"
            "| **SHA512** | 128 hex | Slower | ✅ Very Strong | Rare in TI, file integrity |\n\n"
            "**Key property:** Exact hash match only — one bit difference = completely different hash. "
            "Malware authors bypass by recompiling → different hash, same behavior.\n\n"
            "## Fuzzy / Similarity Hashes\n\n"
            "**ssdeep (CTPH — Context-Triggered Piecewise Hashing)**\n"
            "```bash\n"
            "# Install\n"
            "apt install ssdeep\n\n"
            "# Generate hash\n"
            "ssdeep malware.exe\n\n"
            "# Compare similarity (0-100%, 100=identical)\n"
            "ssdeep -lrm known_malware.exe unknown.exe\n"
            "# Output: 87% match → likely same malware family\n"
            "```\n\n"
            "**tlsh (Trend Micro Locality Sensitive Hash)**\n"
            "```bash\n"
            "# Better than ssdeep for malware clustering\n"
            "tlsh -f malware.exe\n"
            "tlsh -c malware1.exe malware2.exe  # distance score: 0=identical, <100=similar\n"
            "```\n\n"
            "**imphash (Import Hash — PE files only)**\n"
            "```python\n"
            "import pefile\n"
            "pe = pefile.PE('malware.exe')\n"
            "print(pe.get_imphash())  # fingerprints DLL imports\n"
            "# Same malware family compiled differently often shares imphash\n"
            "```\n\n"
            "**richhash (Rich PE header)**\n"
            "- Fingerprints the compiler/linker toolchain\n"
            "- Can cluster malware built with the same build environment\n"
            "- VirusTotal shows this in PE analysis section\n\n"
            "## When to Use Which\n"
            "| Scenario | Hash to Use |\n"
            "|----------|-------------|\n"
            "| Block in EDR/AV | SHA256 |\n"
            "| Search threat intel databases | SHA256 → MD5 fallback |\n"
            "| Find malware variants/family | ssdeep, tlsh |\n"
            "| Cluster similar PE samples | imphash, richhash |\n"
            "| YARA rule development | SHA256 in meta, imphash in condition |\n\n"
            "**Pro tip:** Always collect all four (MD5, SHA1, SHA256, imphash) when analyzing a sample. "
            "Different TI sources index different hash types."
        ),
    },
    # ── EMAIL IOCS ───────────────────────────────────────────────────────────────
    {
        "category": "email_ioc",
        "user": "How do I analyze a suspicious phishing email for IOCs?",
        "assistant": (
            "# Phishing Email IOC Analysis — Step-by-Step\n\n"
            "## Step 1: Safe Email Handling\n"
            "```bash\n"
            "# Export as .eml from Outlook/Gmail (never open attachments directly)\n"
            "# On Linux, open with text editor for header analysis\n"
            "# Use REMnux VM for all attachment analysis\n"
            "```\n\n"
            "## Step 2: Header Analysis\n"
            "```bash\n"
            "# Extract headers from .eml\n"
            "cat phish.eml | grep -iE '^(from|to|subject|received|x-originating|message-id|return-path|reply-to)'\n\n"
            "# Key header IOCs:\n"
            "# Return-Path ≠ From → spoofing indicator\n"
            "# X-Originating-IP → sender's real IP\n"
            "# Reply-To → different domain than From → BEC indicator\n"
            "# Received headers → trace mail path (bottom to top)\n\n"
            "# Parse with mha (Mail Header Analyzer)\n"
            "pip install mail-parser\n"
            "python3 -c \"import mailparser; m=mailparser.parse_from_file('phish.eml'); print(m.headers)\"\n"
            "```\n\n"
            "## Step 3: SPF/DKIM/DMARC Verification\n"
            "```bash\n"
            "# Check SPF\n"
            "dig +short TXT example.com | grep spf\n"
            "# Pass/Fail/Neutral in email headers:\n"
            "# Authentication-Results: spf=fail (attackerdomain.com)\n\n"
            "# Online tools:\n"
            "# MXToolbox: https://mxtoolbox.com/EmailHeaders.aspx\n"
            "# Email Header Analyzer: https://toolbox.googleapps.com/apps/messageheader/\n"
            "```\n\n"
            "## Step 4: URL Extraction and Analysis\n"
            "```bash\n"
            "# Extract URLs from email body\n"
            "cat phish.eml | grep -oE 'https?://[^ >\"]+'\n\n"
            "# Defang URLs before sharing (replace . with [.] and :// with ://)\n"
            "# NEVER click directly — use:\n\n"
            "# URLScan.io (passive scan)\n"
            "curl 'https://urlscan.io/api/v1/scan/' \\\n"
            "  -H 'API-Key: YOUR_KEY' \\\n"
            "  -d '{\"url\": \"http://suspicious-url.com\", \"visibility\": \"private\"}'\n\n"
            "# VirusTotal URL check\n"
            "curl 'https://www.virustotal.com/api/v3/urls' \\\n"
            "  -H 'x-apikey: YOUR_VT_KEY' \\\n"
            "  --data-urlencode 'url=http://suspicious-url.com'\n"
            "```\n\n"
            "## Step 5: Attachment Analysis\n"
            "```bash\n"
            "# Calculate hash (without opening)\n"
            "sha256sum attachment.docx\n\n"
            "# Check hash on VT\n"
            "# Detonate in sandbox: https://app.any.run/, https://www.hybrid-analysis.com/\n\n"
            "# Extract macros from Office documents\n"
            "pip install oletools\n"
            "olevba attachment.docm\n"
            "```\n\n"
            "## IOC Extraction Checklist\n"
            "- [ ] Sender email address\n"
            "- [ ] Reply-To address (if different)\n"
            "- [ ] X-Originating-IP\n"
            "- [ ] Sending mail server IP (last Received header)\n"
            "- [ ] All URLs in body and headers\n"
            "- [ ] Attachment SHA256 hashes\n"
            "- [ ] Domain(s) used\n"
            "- [ ] Any phone numbers or BEC account info"
        ),
    },
    # ── URL IOCS ──────────────────────────────────────────────────────────────────
    {
        "category": "url_ioc",
        "user": "A URL was flagged: http://192.168.1.200/wp-content/uploads/2024/shell.php — What does this indicate?",
        "assistant": (
            "# Threat Intelligence Report — URL IOC\n\n"
            "## Indicator Classification\n"
            "**Type:** URL\n"
            "**Category:** Web Shell — PHP Remote Code Execution\n"
            "**Risk Score: 10/10**\n\n"
            "## Analysis\n"
            "This URL exhibits **critical web shell indicators:**\n\n"
            "1. **`/wp-content/uploads/`** — WordPress file upload directory. "
            "This is a **well-known web shell deployment path**. The uploads directory is writable "
            "by the web server and served as static files — perfect for shell upload post-exploitation.\n\n"
            "2. **`shell.php`** — Explicit PHP web shell filename. No legitimate file would be named `shell.php`.\n\n"
            "3. **RFC 1918 IP (192.168.x.x)** — Internal IP indicates this server is on your network. "
            "This is an **internal compromise**, not an external indicator.\n\n"
            "## MITRE ATT&CK Mapping\n"
            "| Technique | ID | Description |\n"
            "|-----------|-----|-------------|\n"
            "| Server Software Component: Web Shell | T1505.003 | PHP web shell planted in uploads dir |\n"
            "| Exploit Public-Facing Application | T1190 | WordPress file upload vulnerability |\n"
            "| Command and Scripting Interpreter: PHP | T1059.006 | PHP execution via web shell |\n\n"
            "## Immediate Response Actions\n"
            "1. **ISOLATE the server immediately** — this is an active compromise\n"
            "2. **Do NOT delete the file yet** — preserve forensic evidence first\n"
            "3. **Block web access** to `/wp-content/uploads/` PHP execution at WAF/nginx:\n"
            "   ```nginx\n"
            "   location ~* /wp-content/uploads/.*\\.php$ {\n"
            "       deny all;\n"
            "       return 403;\n"
            "   }\n"
            "   ```\n"
            "4. **Preserve evidence:**\n"
            "   ```bash\n"
            "   sha256sum shell.php; cp shell.php /evidence/shell.php.bak\n"
            "   tar czf /evidence/uploads_$(date +%F).tar.gz /var/www/html/wp-content/uploads/\n"
            "   ```\n"
            "5. **Review web server access logs** for requests to this shell:\n"
            "   ```bash\n"
            "   grep 'shell.php' /var/log/nginx/access.log | grep -v '404'\n"
            "   # Note: attacker source IPs, User-Agents, POST parameters\n"
            "   ```\n"
            "6. **Check for other web shells** in uploads directory:\n"
            "   ```bash\n"
            "   find /var/www/html/wp-content/uploads/ -name '*.php' -newer /var/www/html/wp-config.php\n"
            "   yara64 -r webshell.yar /var/www/html/wp-content/uploads/\n"
            "   ```\n\n"
            "## Disposition\n"
            "**CRITICAL — Active Compromise. Initiate Incident Response immediately.**"
        ),
    },
    # ── THREAT INTEL FEEDS ────────────────────────────────────────────────────────
    {
        "category": "threat_intel",
        "user": "What are the best free threat intelligence feeds I can integrate into my SIEM?",
        "assistant": (
            "# Free Threat Intelligence Feeds — SIEM Integration Guide\n\n"
            "## Top Free TI Feeds by Category\n\n"
            "### IP/Network Blocklists\n"
            "| Feed | URL | Update Freq | Format |\n"
            "|------|-----|-------------|--------|\n"
            "| Spamhaus DROP/EDROP | spamhaus.org/drop | Daily | TXT |\n"
            "| Emerging Threats (ET) | rules.emergingthreats.net | Daily | Various |\n"
            "| CINS Score | cinsscore.com/list/ci-badguys.txt | Daily | TXT |\n"
            "| Abuse.ch Feodo | feodotracker.abuse.ch/downloads/ipblocklist.csv | Multiple/day | CSV |\n"
            "| URLhaus IP | urlhaus.abuse.ch/downloads/csv/ | Multiple/day | CSV |\n"
            "| AlienVault OTX | otx.alienvault.com (API) | Realtime | JSON |\n\n"
            "### Domain/URL Feeds\n"
            "| Feed | URL | Notes |\n"
            "|------|-----|-------|\n"
            "| Abuse.ch URLhaus | urlhaus-api.abuse.ch | Active malware URLs |\n"
            "| PhishTank | phishtank.org/developer_info.php | Phishing URLs |\n"
            "| OpenPhish | openphish.com/feed.txt | Phishing URLs |\n"
            "| Cisco Talos BL | talosintelligence.com/documents/ip-blacklist | IP + domains |\n"
            "| Malware Domain List | malwaredomainlist.com | Domain IOCs |\n\n"
            "### Hash/Malware Feeds\n"
            "| Feed | URL | Notes |\n"
            "|------|-----|-------|\n"
            "| MalwareBazaar | bazaar.abuse.ch/api/ | Recent malware hashes |\n"
            "| VirusShare | virusshare.com | Hashes (registration required) |\n"
            "| Malpedia | malpedia.caad.fkie.fraunhofer.de | Malware family intelligence |\n\n"
            "### Vulnerability/CVE Feeds\n"
            "| Feed | URL | Notes |\n"
            "|------|-----|-------|\n"
            "| CISA KEV | cisa.gov/known-exploited-vulnerabilities-catalog | Known exploited CVEs |\n"
            "| NVD | nvd.nist.gov/vuln/data-feeds | All CVEs + CVSS |\n"
            "| VulnDB (free tier) | vuldb.com | Vulnerability intelligence |\n\n"
            "## SIEM Integration Examples\n\n"
            "**Splunk — Threat Intel Framework (STIX/TAXII):**\n"
            "```conf\n"
            "# In inputs.conf — poll URLhaus feed\n"
            "[script://./bin/fetch_ti.py]\n"
            "interval = 3600\n"
            "sourcetype = threat_intel:urlhaus\n"
            "```\n\n"
            "**Elastic — MISP integration:**\n"
            "```yaml\n"
            "# In Elastic MISP integration settings\n"
            "misp_url: https://your-misp-instance.com\n"
            "misp_key: YOUR_API_KEY\n"
            "fetch_interval: 1h\n"
            "```\n\n"
            "**MISP (free open-source TI platform):**\n"
            "```bash\n"
            "# Self-host MISP and subscribe to free feeds\n"
            "# docker-compose up -d  (via MISP Docker)\n"
            "# Subscribe to: CIRCL OSINT Feed, Abuse.ch, MITRE ATT&CK\n"
            "```\n\n"
            "## Integration Architecture\n"
            "```\n"
            "TI Feeds → MISP (normalize + deduplicate) → SIEM lookup tables\n"
            "                                          → EDR block lists\n"
            "                                          → Firewall deny lists\n"
            "                                          → DNS sinkhole/RPZ\n"
            "```"
        ),
    },
    # ── THREAT ACTOR PIVOTING ─────────────────────────────────────────────────
    {
        "category": "threat_actor",
        "user": "I found a C2 IP: 91.92.109.44. How do I pivot from this single IOC to map the full threat actor infrastructure?",
        "assistant": (
            "# IOC Pivoting — Threat Actor Infrastructure Mapping\n\n"
            "## Step 1 — Enrich the seed IOC\n"
            "```\nVirustotal: relations → communicating files, downloaded files, referrer files\n"
            "Shodan: open ports, banners, SSL certs, ASN, history\n"
            "Censys: TLS certificate subjects, issuer, fingerprint (jarm)\n"
            "RiskIQ / Silentpush: passive DNS, host pairs, trackers\n```\n\n"
            "## Step 2 — Certificate pivoting (most powerful)\n"
            "```\n1. Look up SSL cert on Censys/Shodan for 91.92.109.44\n"
            "2. Note Subject CN / SANs / serial number\n"
            "3. Search Censys for other IPs sharing the same cert fingerprint\n"
            "4. Each match = another server in the C2 cluster\n```\n\n"
            "## Step 3 — JARM fingerprint pivoting\n"
            "```bash\npython3 jarm.py 91.92.109.44 443\n"
            "# Hash identifies TLS stack config → search Shodan: ssl.jarm:<hash>\n```\n\n"
            "## Step 4 — Passive DNS\n"
            "- What domains resolved to this IP historically?\n"
            "- What other IPs did those domains resolve to?\n"
            "- Expand the cluster iteratively\n\n"
            "## Step 5 — ASN / hosting pivoting\n"
            "```\nASN lookup → identify the bullet-proof hosting provider\n"
            "Search Shodan/Censys for same port+banner pattern across the ASN\n```\n\n"
            "## Step 6 — Behavioral pivoting\n"
            "- Extract malware samples that contact this IP (MalwareBazaar, VirusTotal)\n"
            "- Identify C2 framework (Cobalt Strike? Metasploit? Sliver?) via banner\n"
            "- Search GitHub/Pastebin for config fragments\n\n"
            "## Output: Infrastructure map\n"
            "Document as a graph: IPs → Domains → Certs → ASNs → Malware samples → TTPs\n"
            "Share via MISP or OpenCTI for team correlation."
        ),
    },
    {
        "category": "threat_actor",
        "user": "What is diamond model analysis and how do I apply it to an incident?",
        "assistant": (
            "# Diamond Model of Intrusion Analysis\n\n"
            "## The Four Vertices\n"
            "```\n        Adversary\n           /\\\n          /  \\\n         /    \\\n   Infra — Capability\n         \\    /\n          \\  /\n           \\/\n          Victim\n```\n\n"
            "| Vertex | What it captures |\n|--------|------------------|\n"
            "| **Adversary** | Threat actor identity, motivation, intent |\n"
            "| **Infrastructure** | IPs, domains, hosting, C2, email providers |\n"
            "| **Capability** | Tools, malware, exploits, TTPs |\n"
            "| **Victim** | Target org, sector, geography, technology |\n\n"
            "## Applying it to an incident\n"
            "1. **Populate each vertex from evidence:**\n"
            "   - Adversary: threat actor group if attributed (e.g., APT29, FIN7)\n"
            "   - Infrastructure: all C2 IPs, domains, email senders\n"
            "   - Capability: malware family, exploits used, lateral movement tools\n"
            "   - Victim: your org, sector, specific assets targeted\n\n"
            "2. **Draw edges** between vertices — each edge = an activity thread\n\n"
            "3. **Pivot across vertices** to find related incidents:\n"
            "   - Same infrastructure → same actor different campaign\n"
            "   - Same capability → different infrastructure (actor changed infra)\n"
            "   - Same victim profile → different actors targeting your sector\n\n"
            "## Intelligence value\n"
            "- Infrastructure and Capability change frequently (easy to swap)\n"
            "- Adversary and Victim profiles are more stable\n"
            "- Focus defenses on the Capability vertex — hardest for actor to change\n\n"
            "**Tools:** MISP galaxy, OpenCTI graph, Maltego, Analyst Notebook"
        ),
    },
    # ── MISP / TI PLATFORMS ───────────────────────────────────────────────────
    {
        "category": "ti_platform",
        "user": "How do I set up MISP for my SOC to share threat intelligence internally and with ISACs?",
        "assistant": (
            "# MISP Deployment for SOC TI Sharing\n\n"
            "## Quick install (Docker)\n"
            "```bash\ngit clone https://github.com/MISP/misp-docker\ncd misp-docker\ncp template.env .env\n# Edit .env: set MISP_BASEURL, admin email/password\ndocker-compose up -d\n```\n\n"
            "## Core configuration\n"
            "1. **Organizations** — create your org, add partner orgs\n"
            "2. **Sharing groups** — define who sees what (internal, ISAC, community)\n"
            "3. **Feeds** — add free TI feeds:\n"
            "   ```\n   CIRCL OSINT Feed, Botvrij.eu, Abuse.ch (URLhaus, MalwareBazaar)\n"
            "   MITRE ATT&CK galaxy, CIRCL CVE feed\n   ```\n"
            "4. **Sync** — connect to partner MISP instances or ISACs via sync agreements\n\n"
            "## Event workflow\n"
            "```\nCreate Event → Add Attributes (IOCs) → Add Tags (TLP, PAP, ATT&CK)\n"
            "→ Add Galaxy clusters (threat actor, malware family) → Publish\n```\n\n"
            "## SIEM integration\n"
            "```bash\n# Export IOCs as STIX2 or CSV for SIEM\ncurl -H 'Authorization: <key>' \\\n"
            "  'https://misp/events/restSearch/json' \\\n  -d '{\"returnFormat\":\"csv\",\"type\":\"ip-dst\",\"to_ids\":true}'\n```\n\n"
            "## TLP tagging\n"
            "| TLP | Share with |\n|-----|------------|\n"
            "| RED | Named individuals only |\n| AMBER | Organization + partners |\n"
            "| GREEN | Community/ISAC |\n| WHITE/CLEAR | Public |"
        ),
    },
    {
        "category": "ti_platform",
        "user": "How do I query OpenCTI or MISP API to automate IOC lookups in my SOAR playbook?",
        "assistant": (
            "# Automating IOC Lookups via MISP / OpenCTI API\n\n"
            "## MISP API — Python lookup\n"
            "```python\nfrom pymisp import PyMISP\n\nmisp = PyMISP('https://misp.corp', 'API_KEY', ssl=True)\n\ndef lookup_ioc(value, ioc_type='ip-dst'):\n"
            "    result = misp.search(value=value, type_attribute=ioc_type,\n"
            "                         to_ids=True, pythonify=True)\n"
            "    if result:\n        for attr in result:\n            print(f'Match: {attr.event_id} | {attr.comment}')\n"
            "        return True\n    return False\n\nlookup_ioc('185.220.101.45', 'ip-dst')\n```\n\n"
            "## OpenCTI API — GraphQL lookup\n"
            "```python\nfrom pycti import OpenCTIApiClient\n\nctI = OpenCTIApiClient('https://opencti.corp', 'TOKEN')\n\ndef lookup_observable(value):\n"
            "    obs = cti.stix_cyber_observable.read(filters=[\n"
            "        {'key': 'value', 'values': [value]}\n    ])\n"
            "    return obs\n```\n\n"
            "## SOAR integration pattern\n"
            "```\nAlert fires → Extract IOCs (IPs/domains/hashes)\n"
            "→ Query MISP/OpenCTI API → Enrich alert context\n"
            "→ If known malicious: auto-block + escalate\n"
            "→ If unknown: submit to sandbox + TI enrichment\n"
            "→ Update MISP event with new findings\n```\n\n"
            "## Rate limiting / caching\n"
            "- Cache MISP lookups in Redis (TTL 1h) to avoid hammering API\n"
            "- Batch lookups: MISP `/attributes/restSearch` accepts arrays\n"
            "- For VT: use 4 lookups/min free tier; cache results 24h"
        ),
    },
    # ── SANDBOX ANALYSIS ──────────────────────────────────────────────────────
    {
        "category": "sandbox_analysis",
        "user": "A suspicious .exe was attached to a phishing email. Walk me through analyzing it with a sandbox and extracting IOCs.",
        "assistant": (
            "# Malware Sandbox Analysis Workflow\n\n"
            "## Step 1 — Pre-analysis (static, safe)\n"
            "```bash\n# Hash and check VirusTotal first\nsha256sum suspicious.exe\n"
            "curl -s 'https://www.virustotal.com/api/v3/files/<sha256>' \\\n  -H 'x-apikey: VT_KEY'\n\n"
            "# File type identification\nfile suspicious.exe\nexiftool suspicious.exe\nstrings suspicious.exe | grep -E 'http|cmd|powershell|reg'\n```\n\n"
            "## Step 2 — Sandbox submission\n"
            "**Free sandboxes:**\n"
            "| Sandbox | Strength |\n|---------|----------|\n"
            "| Any.run | Interactive, real-time, free tier |\n"
            "| Joe Sandbox Cloud | Deep behavioral analysis |\n"
            "| Triage (tria.ge) | Fast, CAPE-based, API available |\n"
            "| Hybrid Analysis | VxStream, good static+dynamic |\n\n"
            "## Step 3 — Extract IOCs from report\n"
            "```\nNetwork: C2 IPs/domains/URLs, DNS queries, HTTP requests\n"
            "Files: dropped files (hashes), modified registry keys, new services\n"
            "Processes: spawned child processes, injected processes\n"
            "Mutex: unique mutex names (persistence fingerprint)\n```\n\n"
            "## Step 4 — ATT&CK mapping\n"
            "Map behaviors to MITRE ATT&CK:\n"
            "- Process injection → T1055\n- Persistence via Run key → T1547.001\n"
            "- C2 over HTTP → T1071.001\n- Credential dumping → T1003\n\n"
            "## Step 5 — Block and document\n"
            "```\nBlock C2 IPs/domains → Firewall / DNS sinkhole\n"
            "Block file hash → EDR exclusion list\nAdd to MISP event\nNotify affected users\n```"
        ),
    },
    {
        "category": "sandbox_analysis",
        "user": "How do I set up a local Cuckoo or CAPE sandbox for offline malware analysis?",
        "assistant": (
            "# Local Malware Sandbox Setup — CAPE Sandbox\n\n"
            "## Why CAPE over Cuckoo\n"
            "CAPE (Cuckoo Analysis + Payload Extraction) is the actively maintained fork:\n"
            "- Automated payload extraction (unpacking)\n- Config extraction for 100+ malware families\n"
            "- Actively maintained (Cuckoo is EOL)\n\n"
            "## Setup (Ubuntu 22.04 host)\n"
            "```bash\n# Prerequisites\napt install python3 python3-pip git mongodb postgresql\n\n"
            "# Clone CAPE\ngit clone https://github.com/kevoreilly/CAPEv2\ncd CAPEv2\npip3 install -r requirements.txt\n\n"
            "# Create Windows 10 guest VM in KVM/VirtualBox\n# Install Python 2.7 + CAPE agent on guest\n"
            "# Snapshot: cuckoo1\n\n# Configure cape.conf\n[cuckoo]\nmachinery = kvm\n[resultserver]\nip = 192.168.56.1\n```\n\n"
            "## Network isolation (critical)\n"
            "```\nHost: NAT interface (host can reach internet, sandbox cannot)\n"
            "Guest-only network: 192.168.56.0/24\n"
            "INetSim on host: simulates internet services (DNS, HTTP, SMTP)\n"
            "Fake internet: malware makes C2 requests → captured by INetSim\n```\n\n"
            "## Submitting samples\n"
            "```bash\ncape submit /path/to/sample.exe\ncape submit --url 'http://phishing.example/payload'\n"
            "# Web UI at http://localhost:8000\n```\n\n"
            "## Key output: extracted configs\n"
            "CAPE automatically extracts C2 configs from common families:\n"
            "Cobalt Strike, Emotet, Qakbot, Remcos, AsyncRAT, NjRAT"
        ),
    },
    # ── HASH / FILE ANALYSIS ─────────────────────────────────────────────────
    {
        "category": "hash_analysis",
        "user": "How do I use SSDEEP and TLSH fuzzy hashing to find malware variants that evade exact hash detection?",
        "assistant": (
            "# Fuzzy Hash Malware Detection — SSDEEP & TLSH\n\n"
            "## Why fuzzy hashing?\n"
            "Malware authors change one byte → SHA256 changes completely.\n"
            "Fuzzy hashes measure **similarity** (0–100%) between files.\n\n"
            "## SSDEEP\n"
            "```bash\n# Install\napt install ssdeep\n\n# Hash a file\nssdeep -r /malware/ > malware.ssdeep\n\n"
            "# Compare a sample against known hashes\nssdeep -m malware.ssdeep unknown_sample.exe\n\n"
            "# Output: score 0-100 (>50 = likely variant)\nssdeep -m baseline.ssdeep new_sample.bin\n"
            "  new_sample.bin matches known_mal.exe (score: 78)\n```\n\n"
            "## TLSH (Trend Micro Locality Sensitive Hash)\n"
            "```python\nimport tlsh\n\nwith open('sample1.exe', 'rb') as f:\n    h1 = tlsh.hash(f.read())\n"
            "with open('sample2.exe', 'rb') as f:\n    h2 = tlsh.hash(f.read())\n\ndiff = tlsh.diff(h1, h2)\nprint(f'TLSH diff score: {diff}')  # <300 = similar\n```\n\n"
            "## Building a hunt\n"
            "```python\nimport ssdeep, os\n\nbaseline_hash = ssdeep.hash(open('cobalt_strike.exe', 'rb').read())\n\nfor root, dirs, files in os.walk('/samples'):\n"
            "    for fname in files:\n        fpath = os.path.join(root, fname)\n"
            "        candidate = ssdeep.hash(open(fpath, 'rb').read())\n"
            "        score = ssdeep.compare(baseline_hash, candidate)\n"
            "        if score > 40:\n            print(f'Variant: {fpath} (score {score})')\n```\n\n"
            "## VirusTotal integration\n"
            "VT stores SSDEEP hashes — use `/files/{hash}/similar_files` endpoint\n"
            "to find family variants automatically."
        ),
    },
    # ── CVE / VULNERABILITY IOC ───────────────────────────────────────────────
    {
        "category": "vuln_ioc",
        "user": "CVE-2024-3400 is being actively exploited in my industry. How do I generate threat intelligence and detection rules from a CVE?",
        "assistant": (
            "# CVE-to-Detection Intelligence Pipeline\n\n"
            "## Step 1 — Understand the CVE\n"
            "```bash\n# NIST NVD\ncurl 'https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2024-3400'\n\n"
            "# CISA KEV — is it in active exploitation list?\ncurl 'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json' | \\\n"
            "  python3 -c \"import json,sys; d=json.load(sys.stdin); [print(v['cveID']) for v in d['vulnerabilities'] if 'CVE-2024-3400' in v['cveID']]\"\n```\n\n"
            "## Step 2 — Find exploitation indicators\n"
            "Sources for exploit IOCs:\n"
            "- GitHub: search `CVE-2024-3400 exploit` for PoC code\n"
            "- ExploitDB: `searchsploit CVE-2024-3400`\n"
            "- Greynoise/Shodan: scan activity targeting the port/service\n"
            "- Twitter/X / Mastodon: threat intel community sharing\n\n"
            "## Step 3 — Extract network indicators\n"
            "From PoC code and live reports:\n"
            "- Attacker IPs hitting the vulnerable endpoint\n"
            "- Payloads in HTTP requests (User-Agent, URL paths, POST body patterns)\n"
            "- C2 domains/IPs dropped post-exploitation\n\n"
            "## Step 4 — Create detection rules\n"
            "```yaml\n# Sigma rule for CVE-2024-3400 (PAN-OS command injection)\ntitle: PAN-OS CVE-2024-3400 Exploit Attempt\nstatus: experimental\nlogsource:\n"
            "    category: webserver\ndetection:\n    selection:\n        cs-uri-query|contains:\n"
            "            - '/../../../'\n            - '%2F..%2F..%2F'\n        cs-uri-stem: '/ssl-vpn/hipreport.esp'\n"
            "    condition: selection\n```\n\n"
            "## Step 5 — Assess your exposure\n"
            "```bash\n# Check if you have vulnerable systems\nnmap -p 443 --script http-title <range> | grep 'GlobalProtect'\n"
            "# Or query your asset inventory for PAN-OS versions\n```"
        ),
    },
    # ── EMAIL IOC ──────────────────────────────────────────────────────────────
    {
        "category": "email_ioc",
        "user": "How do I extract and analyze IOCs from a .eml phishing email file?",
        "assistant": (
            "# Phishing Email IOC Extraction\n\n"
            "## Tools\n"
            "```bash\npip install oletools PhishingKitHunter\napt install mailutils\n```\n\n"
            "## Step 1 — Parse email headers\n"
            "```python\nimport email, re\n\nwith open('phishing.eml') as f:\n    msg = email.message_from_file(f)\n\n"
            "print('From:', msg['From'])\nprint('Reply-To:', msg['Reply-To'])\nprint('X-Originating-IP:', msg.get('X-Originating-IP'))\n\n"
            "# Extract all Received headers for hop analysis\nfor header in msg.get_all('Received', []):\n    print('Received:', header)\n```\n\n"
            "## Step 2 — Extract URLs\n"
            "```python\nfrom bs4 import BeautifulSoup\n\nbody = ''\nfor part in msg.walk():\n"
            "    if part.get_content_type() == 'text/html':\n        body += part.get_payload(decode=True).decode('utf-8', errors='ignore')\n\n"
            "soup = BeautifulSoup(body, 'html.parser')\nurls = [a['href'] for a in soup.find_all('a', href=True)]\nprint('URLs:', urls)\n```\n\n"
            "## Step 3 — Analyze attachments\n"
            "```python\nfor part in msg.walk():\n    if part.get_filename():\n"
            "        payload = part.get_payload(decode=True)\n        import hashlib\n"
            "        sha256 = hashlib.sha256(payload).hexdigest()\n"
            "        print(f'Attachment: {part.get_filename()} SHA256: {sha256}')\n"
            "        with open(f'/tmp/{part.get_filename()}', 'wb') as f:\n            f.write(payload)\n```\n\n"
            "## Step 4 — Check SPF/DKIM/DMARC\n"
            "```bash\n# Validate sender authentication\npython3 -m spf 'ip' 'sender@domain.com' 'domain.com'\n"
            "# Check DKIM signature in headers\ngrep -i 'dkim-signature' phishing.eml\n```\n\n"
            "## IOC summary template\n"
            "```\nSender IP: x.x.x.x (SPF: fail/pass)\nSender domain: phishing.com (registered: 2024-01-01)\n"
            "URLs: [list]\nAttachments: [filename, sha256, type]\nSubject: [subject]\n```"
        ),
    },
    # ── NETWORK IOC ───────────────────────────────────────────────────────────
    {
        "category": "network_ioc",
        "user": "How do I create and maintain a blocklist using threat intel IOCs in my firewall and DNS?",
        "assistant": (
            "# Automated IOC Blocklist Management\n\n"
            "## Architecture\n"
            "```\nTI Feeds → Aggregator Script → Deduplicate/Validate\n"
            "         → Firewall API  (IP blocks)\n"
            "         → DNS RPZ       (domain sinkhole)\n"
            "         → Proxy policy  (URL blocks)\n```\n\n"
            "## IP blocklist script\n"
            "```python\nimport requests, ipaddress\n\nFEEDS = {\n"
            "    'emerging_threats': 'https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt',\n"
            "    'abuse_ch_feodo': 'https://feodotracker.abuse.ch/downloads/ipblocklist.txt',\n"
            "    'cinsscore': 'http://cinsscore.com/list/ci-badguys.txt',\n}\n\n"
            "def fetch_ips(url):\n    r = requests.get(url, timeout=30)\n"
            "    ips = []\n    for line in r.text.splitlines():\n"
            "        line = line.strip()\n        if line and not line.startswith('#'):\n"
            "            try:\n                ipaddress.ip_address(line)\n                ips.append(line)\n"
            "            except ValueError: pass\n    return ips\n\n"
            "all_ips = set()\nfor name, url in FEEDS.items():\n    ips = fetch_ips(url)\n"
            "    all_ips.update(ips)\n    print(f'{name}: {len(ips)} IPs')\n\n"
            "with open('/etc/firewall/blocklist.txt', 'w') as f:\n    f.write('\\n'.join(sorted(all_ips)))\n```\n\n"
            "## DNS Response Policy Zone (RPZ)\n"
            "```bind\n; /etc/bind/rpz.zone\n$TTL 60\n@ IN SOA localhost. root.localhost. ( 1 1h 15m 30d 2h )\n"
            "  IN NS  localhost.\n\n; Malicious domains → NXDOMAIN\nphishing.example.com  CNAME .\nevil-c2.net            CNAME .\n```\n\n"
            "## Automation\n"
            "```bash\n# Cron job: refresh blocklists every 4h\n0 */4 * * * python3 /opt/ti/update_blocklist.py && \\\n"
            "           rndc reload rpz && \\\n           ipset restore < /etc/firewall/blocklist.ipset\n```"
        ),
    },
    {
        "category": "network_ioc",
        "user": "What is passive DNS and how do I use it to investigate suspicious domain activity?",
        "assistant": (
            "# Passive DNS for Threat Investigation\n\n"
            "## What is Passive DNS?\n"
            "A historical database of DNS resolutions observed in the wild:\n"
            "- **When** a domain resolved to an IP\n- **What IP** it resolved to\n"
            "- **How long** the resolution was active (first/last seen)\n\n"
            "Collected by DNS sensors on resolver networks worldwide.\n\n"
            "## Free PDNS sources\n"
            "| Source | Coverage | API |\n|--------|----------|-----|\n"
            "| SecurityTrails | Excellent | Free tier: 50/mo |\n| VirusTotal | Good | Free tier: 4/min |\n"
            "| Shodan | Limited | Free account |\n| PassiveTotal (RiskIQ) | Excellent | Free tier |\n"
            "| CIRCL PDNS | EU-focused | Free, REST API |\n\n"
            "## Investigation workflow\n"
            "```python\nimport requests\n\n# VirusTotal PDNS\ndef vt_pdns_domain(domain, api_key):\n"
            "    url = f'https://www.virustotal.com/api/v3/domains/{domain}/resolutions'\n"
            "    r = requests.get(url, headers={'x-apikey': api_key})\n"
            "    return r.json()\n\ndef vt_pdns_ip(ip, api_key):\n"
            "    url = f'https://www.virustotal.com/api/v3/ip_addresses/{ip}/resolutions'\n"
            "    r = requests.get(url, headers={'x-apikey': api_key})\n"
            "    return r.json()\n```\n\n"
            "## Key analysis questions\n"
            "- What IPs did this domain resolve to historically? → find previous C2 infra\n"
            "- When was the domain registered vs. first DNS activity? → fresh domains = suspicious\n"
            "- What other domains shared this IP? → identify related campaigns\n"
            "- Did the IP change recently? → possible infrastructure migration\n\n"
            "## Red flags\n"
            "- Domain registered <30 days ago with C2-like traffic\n"
            "- IP shared by 50+ suspicious domains (shared bulletproof hosting)\n"
            "- Domain uses fast-flux (IP changes every few minutes)"
        ),
    },
    # ── STIX/TAXII ────────────────────────────────────────────────────────────
    {
        "category": "ti_standards",
        "user": "Explain STIX 2.1 and TAXII 2.1 and show me how to publish and consume threat intel with them.",
        "assistant": (
            "# STIX 2.1 + TAXII 2.1 — Structured Threat Intel Exchange\n\n"
            "## STIX 2.1 — Threat Intelligence Language\n"
            "Objects (SDOs): Indicator, Malware, ThreatActor, AttackPattern, Campaign, "
            "CourseOfAction, Tool, Vulnerability, Report, Identity, Relationship\n\n"
            "```python\nimport json\nfrom stix2 import Indicator, Malware, Relationship, Bundle\n\n"
            "malware = Malware(name='QakBot', malware_types=['trojan'], is_family=True)\n\n"
            "indicator = Indicator(\n    name='QakBot C2 IP',\n"
            "    pattern=\"[ipv4-addr:value = '91.92.109.44']\",\n"
            "    pattern_type='stix',\n    valid_from='2024-01-01T00:00:00Z',\n"
            "    indicator_types=['malicious-activity'],\n)\n\n"
            "rel = Relationship(relationship_type='indicates',\n"
            "                   source_ref=indicator.id,\n                   target_ref=malware.id)\n\n"
            "bundle = Bundle(objects=[malware, indicator, rel])\nprint(bundle.serialize(pretty=True))\n```\n\n"
            "## TAXII 2.1 — Transport Protocol\n"
            "```python\nfrom taxii2client.v21 import Server\n\n"
            "# Connect to TAXII server (e.g., MITRE ATT&CK)\nserver = Server('https://cti-taxii.mitre.org/taxii/',\n"
            "                user='guest', password='guest')\n\ncollection = server.api_roots[0].collections[0]\n"
            "for envelope in collection.get_objects():\n    for obj in envelope.get('objects', []):\n"
            "        if obj['type'] == 'attack-pattern':\n            print(obj['name'])\n```\n\n"
            "## SIEM ingestion of STIX\n"
            "```bash\n# Elastic has native STIX integration\n# Or convert to CSV for Splunk:\npython3 -c \"\nimport json\nbundle = json.load(open('intel.json'))\n"
            "for obj in bundle['objects']:\n    if obj['type'] == 'indicator':\n        print(obj['pattern'])\n\"\n```"
        ),
    },
    # ── CERTIFICATE IOC ────────────────────────────────────────────────────────
    {
        "category": "cert_ioc",
        "user": "How do I detect malicious or self-signed certificates used in C2 communications?",
        "assistant": (
            "# Malicious Certificate Detection for C2 Hunting\n\n"
            "## Why attackers use TLS\n"
            "- Encrypts C2 traffic (evades payload inspection)\n"
            "- Blends with legitimate HTTPS traffic\n"
            "- Self-signed or Let's Encrypt certs are free and easy\n\n"
            "## Detection signals\n"
            "### 1. JARM fingerprinting (framework detection)\n"
            "```bash\npip install jarm-py\n\n# Fingerprint a suspicious server\npython3 jarm.py suspicious.server.com 443\n\n"
            "# Compare against known C2 JARM hashes:\n# Cobalt Strike default: 07d14d16d21d21d07c42d41d00041d24a458a375eef0c576d23a7bab9a9fb1\n"
            "# Metasploit:          07d19d1ad21d21d07c42d43d000000d24a458a375eef0c576d23a7bab9a9fb1\n```\n\n"
            "### 2. Certificate transparency log hunting\n"
            "```bash\n# crt.sh — search for suspicious cert patterns\ncurl 'https://crt.sh/?q=%25.evil-domain.com&output=json' | python3 -m json.tool\n\n"
            "# Hunt for LOLDomain patterns (typosquatting, keyword abuse)\ncurl 'https://crt.sh/?q=%25microsoft-update%25&output=json'\n```\n\n"
            "### 3. Zeek/Suricata SSL log analysis\n"
            "```sql\n-- Zeek ssl.log: flag self-signed certs with short validity\nSELECT server_name, issuer, subject, not_valid_after\nFROM ssl_logs\nWHERE issuer = subject  -- self-signed\n"
            "  AND DATEDIFF(not_valid_after, not_valid_before) < 365\n  AND server_name NOT IN (SELECT domain FROM whitelist)\n```\n\n"
            "### 4. Certificate field anomalies\n"
            "Red flags in TLS certs:\n"
            "- Issuer = Subject (self-signed)\n- Subject CN = IP address\n"
            "- Validity period exactly 1 year from today (auto-generated)\n"
            "- Generic subject: `O=Internet Widgits, CN=example`\n"
            "- Let's Encrypt cert on non-standard port\n\n"
            "### 5. Network-level hunting with Suricata\n"
            "```yaml\nalert tls any any -> any any (msg:'Self-Signed Cert Detected';\n"
            "  tls.cert_issuer; content:'Internet Widgits';\n  classtype:policy-violation; sid:9001001;)\n```"
        ),
    },
    # ── THREAT HUNTING IOC ────────────────────────────────────────────────────
    {
        "category": "threat_hunting",
        "user": "How do I use threat intel IOCs to drive a proactive threat hunt in my environment?",
        "assistant": (
            "# IOC-Driven Threat Hunting\n\n"
            "## Hunt workflow\n"
            "```\n1. Select Intel → 2. Form Hypothesis → 3. Define Hunt Scope\n"
            "→ 4. Query Data → 5. Triage Results → 6. Escalate or Document\n```\n\n"
            "## Step 1 — Select high-confidence IOCs\n"
            "Prioritize:\n"
            "- IOCs from ISACs matching your industry\n- Actively exploited CVEs (CISA KEV)\n"
            "- APT groups known to target your sector\n"
            "- Behavioral patterns (TTPs) over fragile atomic IOCs (IPs rotate)\n\n"
            "## Step 2 — Form hypothesis\n"
            "Example: *'APT29 is known to use Cobalt Strike with JARM hash X. "
            "If we're targeted, we'd see outbound TLS to non-categorized domains "
            "with this JARM fingerprint.'*\n\n"
            "## Step 3 — Query across data sources\n"
            "```sql\n-- Splunk: hunt for known C2 IP in proxy logs\nindex=proxy dest_ip IN (\"91.92.109.44\",\"45.33.32.156\")\n| stats count by src_ip, dest_ip, dest_port\n\n"
            "-- Hunt for DNS queries to known malicious domains\nindex=dns query IN (\"evil-c2.net\", \"update-microsoft-security.com\")\n```\n\n"
            "## Step 4 — Behavioral hunt (TTPs)\n"
            "```sql\n-- Beaconing detection: regular periodic outbound connections\nindex=netflow dest_port=443 NOT dest_ip IN (cloudflare_ranges)\n| bucket span=1h _time\n"
            "| stats count by src_ip, dest_ip, _time\n| eventstats stdev(count) as stdev, avg(count) as avg by src_ip, dest_ip\n"
            "| where stdev < 2 AND count > 10  -- low variance = beaconing\n```\n\n"
            "## Step 5 — Document findings\n"
            "- True positive → create incident, isolate host\n- False positive → add to tuning list\n"
            "- No finding → document 'No evidence of compromise as of [date]'\n"
            "All hunts should produce a hunt report regardless of outcome."
        ),
    },
]


def generate():
    samples = []
    for item in KB:
        samples.append({
            "messages": [
                {"role": "system",    "content": HANCOCK_SYSTEM},
                {"role": "user",      "content": item["user"]},
                {"role": "assistant", "content": item["assistant"]},
            ]
        })
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        json.dump(samples, f, indent=2)
    print(f"[ioc_kb] ✅ {len(samples)} samples → {OUTPUT_FILE}")
    return samples


if __name__ == "__main__":
    generate()
