"""
IOC Threat Intelligence Knowledge Base — Hancock CyberViser
Q&A pairs for IOC enrichment and threat intelligence analysis.
Outputs: data/raw_ioc_kb.json
"""
import json
from pathlib import Path

OUTPUT_FILE = Path(__file__).parent.parent / "data" / "raw_ioc_kb.json"

HANCOCK_SYSTEM = (
    "You are Hancock IOC, CyberViser's threat intelligence analyst. "
    "When given an indicator of compromise (IP address, domain, URL, file hash, or email), "
    "you provide a structured enrichment report covering: indicator type and classification, "
    "threat intelligence context (known malware families, threat actors, campaigns), "
    "MITRE ATT&CK techniques, risk score (1-10) with justification, "
    "recommended defensive actions, and relevant CVEs if applicable. "
    "Format your response as a clear, structured threat intel report."
)

KB = [
    # ── IP ADDRESS IOCS ───────────────────────────────────────────────────────────
    {
        "category": "ip_ioc",
        "user": "Analyze this suspicious IP: 185.220.101.45 — it appeared in our firewall logs making repeated connection attempts on port 443.",
        "assistant": (
            "# Threat Intelligence Report — IP: 185.220.101.45\n\n"
            "## Indicator Classification\n"
            "**Type:** IPv4 Address\n"
            "**Category:** Tor Exit Node / Scanning Infrastructure\n"
            "**Risk Score: 7/10**\n\n"
            "## Threat Intelligence Context\n"
            "IP 185.220.101.45 is a well-documented **Tor exit node** (confirmed in multiple public threat intel feeds). "
            "Tor exit nodes are routinely used by:\n"
            "- Threat actors for anonymous C2 communications\n"
            "- Ransomware operators during initial access phase\n"
            "- Credential stuffing and brute-force campaigns\n"
            "- ProxyBot/SOCKS5 relay networks\n\n"
            "Historically associated with: **Cobalt Strike beacon callbacks**, **REvil/Sodinokibi** infrastructure, "
            "and general scanning activity.\n\n"
            "## MITRE ATT&CK Mapping\n"
            "| Technique | ID | Description |\n"
            "|-----------|-----|-------------|\n"
            "| Proxy: Multi-hop Proxy | T1090.003 | Tor exit node anonymization |\n"
            "| Reconnaissance: Network Scanning | T1595 | Port 443 scanning activity |\n"
            "| Command and Control | T1071.001 | HTTPS-based C2 via Tor |\n\n"
            "## Verification Steps\n"
            "```bash\n"
            "# Check Tor exit node status:\n"
            "curl https://check.torproject.org/cgi-bin/TorBulkExitList.py | grep 185.220.101.45\n\n"
            "# Enrich with multiple sources:\n"
            "# VirusTotal: https://www.virustotal.com/gui/ip-address/185.220.101.45\n"
            "# Shodan: https://www.shodan.io/host/185.220.101.45\n"
            "# AbuseIPDB: https://www.abuseipdb.com/check/185.220.101.45\n"
            "# AlienVault OTX: https://otx.alienvault.com/indicator/ip/185.220.101.45\n"
            "```\n\n"
            "## Recommended Actions\n"
            "1. **Block** — Add to firewall deny list; Tor exits rarely have legitimate business use\n"
            "2. **Investigate** — Review all connections from this IP in the last 30 days:\n"
            "   ```spl\n"
            "   index=firewall src_ip=185.220.101.45 | table _time, dest_ip, dest_port, bytes_in, bytes_out\n"
            "   ```\n"
            "3. **Check for beaconing** — Regular intervals to this IP may indicate active C2\n"
            "4. **Threat hunt** — Identify any hosts that initiated connections *to* this IP\n\n"
            "## Disposition\n"
            "**BLOCK** — High confidence malicious infrastructure. No legitimate business justification for Tor exit node traffic."
        ),
    },
    {
        "category": "ip_ioc",
        "user": "How do I enrich an IP address IOC? What tools and process should I use?",
        "assistant": (
            "# IOC Enrichment Process — IP Address\n\n"
            "## Step 1: Classify the IP\n"
            "Before enriching, determine context:\n"
            "- Is it external (public) or internal (RFC 1918)?\n"
            "- Is it a source (attacker) or destination (C2/exfil)?\n"
            "- What protocol/port was involved?\n\n"
            "## Step 2: Automated Enrichment (Priority Order)\n\n"
            "**Free Tier Sources:**\n"
            "| Tool | What it provides | API? |\n"
            "|------|------------------|------|\n"
            "| VirusTotal | AV vendor detections, community scores | Yes (free) |\n"
            "| Shodan | Open ports, banner data, ASN, CVEs | Yes (free limited) |\n"
            "| AbuseIPDB | Abuse reports, categories, confidence | Yes (free) |\n"
            "| AlienVault OTX | Threat intel pulses, malware families | Yes (free) |\n"
            "| GreyNoise | Mass internet scanners, Tor nodes | Yes (free tier) |\n"
            "| IPVoid | Multi-source blacklist check | Web only |\n\n"
            "**Paid/Enterprise:**\n"
            "- Recorded Future, Mandiant Advantage, ThreatConnect, MISP\n\n"
            "## Step 3: OSINT Checks\n"
            "```bash\n"
            "# Reverse DNS\n"
            "dig -x <IP>\n"
            "host <IP>\n\n"
            "# ASN/Org lookup\n"
            "whois <IP> | grep -i 'asn\\|org\\|netname'\n"
            "curl https://ipinfo.io/<IP>\n\n"
            "# Shodan CLI\n"
            "shodan host <IP>\n\n"
            "# GreyNoise — is it a mass scanner?\n"
            "curl 'https://api.greynoise.io/v3/community/<IP>'\n"
            "```\n\n"
            "## Step 4: Context from Your Environment\n"
            "```spl\n"
            "# Splunk: All activity involving this IP (last 30 days)\n"
            "index=* (src_ip=<IP> OR dest_ip=<IP>)\n"
            "| stats count by index, sourcetype, src_ip, dest_ip, dest_port\n"
            "| sort -count\n"
            "```\n\n"
            "## Step 5: Scoring & Disposition\n"
            "| Score | Criteria | Action |\n"
            "|-------|----------|--------|\n"
            "| 9–10 | Known C2, malware, active TI alerts | Block + Escalate |\n"
            "| 7–8 | Multiple TI detections, Tor, VPN abuse | Block |\n"
            "| 5–6 | Scanning infrastructure, some TI hits | Monitor + Alert |\n"
            "| 1–4 | Few detections, CDN, legitimate infra | Investigate further |\n\n"
            "## Automation\n"
            "```python\n"
            "# Quick multi-source enrichment script\n"
            "import requests\n\n"
            "def enrich_ip(ip: str):\n"
            "    vt = requests.get(f'https://www.virustotal.com/api/v3/ip_addresses/{ip}',\n"
            "                      headers={'x-apikey': 'YOUR_VT_KEY'}).json()\n"
            "    malicious = vt['data']['attributes']['last_analysis_stats']['malicious']\n"
            "    print(f'VT malicious detections: {malicious}/90')\n"
            "```"
        ),
    },
    # ── DOMAIN IOCS ──────────────────────────────────────────────────────────────
    {
        "category": "domain_ioc",
        "user": "I have a suspicious domain: update-microsoft-security.com — it appeared in DNS logs. How do I analyze it?",
        "assistant": (
            "# Threat Intelligence Report — Domain: update-microsoft-security.com\n\n"
            "## Indicator Classification\n"
            "**Type:** Domain Name\n"
            "**Category:** Typosquatting / Phishing / Potential C2\n"
            "**Risk Score: 8/10**\n\n"
            "## Initial Assessment\n"
            "This domain exhibits **classic malicious domain characteristics:**\n"
            "- **Typosquatting:** impersonates Microsoft using 'microsoft-security' pattern\n"
            "- **Newly registered** (check below) — malicious domains are often <30 days old\n"
            "- **Suspicious TLD usage:** `.com` for impersonation (legitimate Microsoft uses `microsoft.com`)\n"
            "- **Compound keywords:** combining 'update' + 'microsoft' + 'security' = social engineering pattern\n\n"
            "## Enrichment Steps\n"
            "```bash\n"
            "# Registration date (newly registered = higher risk)\n"
            "whois update-microsoft-security.com | grep -i 'creat\\|registr'\n\n"
            "# DNS resolution\n"
            "dig +short update-microsoft-security.com A\n"
            "dig +short update-microsoft-security.com MX\n"
            "dig +short update-microsoft-security.com TXT\n\n"
            "# Certificate transparency logs (subdomains, related certs)\n"
            "curl 'https://crt.sh/?q=update-microsoft-security.com&output=json'\n\n"
            "# Passive DNS (historical resolutions)\n"
            "# → VirusTotal: https://www.virustotal.com/gui/domain/update-microsoft-security.com\n"
            "# → SecurityTrails: https://securitytrails.com/domain/update-microsoft-security.com/dns\n"
            "# → RiskIQ: https://community.riskiq.com\n\n"
            "# URL scan (if URL is known)\n"
            "curl 'https://urlscan.io/api/v1/scan/' -d '{\"url\":\"http://update-microsoft-security.com\"}'\n"
            "```\n\n"
            "## MITRE ATT&CK Mapping\n"
            "| Technique | ID |\n"
            "|-----------|-----|\n"
            "| Phishing | T1566 |\n"
            "| Domain Generation Algorithm / C2 | T1568 |\n"
            "| Masquerading | T1036 |\n\n"
            "## Recommended Actions\n"
            "1. **Block at DNS resolver** (Pi-hole, Bluecoat, Cisco Umbrella, Windows DNS RPZ)\n"
            "2. **Block at proxy/web filter** — add to URL category 'malicious'\n"
            "3. **Investigate DNS logs** for which internal hosts resolved this domain:\n"
            "   ```spl\n"
            "   index=dns query=update-microsoft-security.com | stats count by src_ip, _time\n"
            "   ```\n"
            "4. **Identify affected hosts** — any host that resolved it may have received a phishing email\n"
            "5. **Check email gateway** — search for emails containing this domain\n\n"
            "## Disposition\n"
            "**BLOCK + INVESTIGATE** — Highly suspicious impersonation domain. "
            "Treat any host that resolved this as potentially compromised until proven otherwise."
        ),
    },
    {
        "category": "domain_ioc",
        "user": "What are DGA domains and how do I detect them in my environment?",
        "assistant": (
            "# Domain Generation Algorithm (DGA) Detection Guide\n\n"
            "## What are DGA Domains?\n"
            "Malware generates domain names algorithmically (using a seed like date/time) to create "
            "thousands of potential C2 domains. The attacker registers just a few — the malware tries "
            "all of them until one resolves. This evades static domain blocklists.\n\n"
            "**Common DGA malware families:**\n"
            "- Cryptolocker, Conficker, Ramnit, GameOver Zeus\n"
            "- Dridex, Emotet (hybrid DGA), Suppobox\n"
            "- Bumblebee, Qakbot (modern examples)\n\n"
            "## DGA Domain Characteristics\n"
            "| Indicator | Example | Legitimate |\n"
            "|-----------|---------|------------|\n"
            "| Random-looking string | `xkqpvntlhj.com` | `google.com` |\n"
            "| High consonant ratio | `bxvzqkplm.net` | readable words |\n"
            "| Short registration age | 1–7 days | years |\n"
            "| NXDOMAIN responses | 95%+ fail | rare failure |\n"
            "| No matching MX/TXT | DNS-only | usually has MX |\n"
            "| Low Alexa/Tranco rank | not ranked | top 1M |\n\n"
            "## Detection in Splunk\n"
            "```spl\n"
            "index=dns message_type=QUERY\n"
            "| eval domain_len=len(query)\n"
            "| eval digits=len(replace(query, \"[^0-9]\", \"\"))\n"
            "| eval consonants=len(replace(lower(query), \"[^bcdfghjklmnpqrstvwxyz.\\\\-]\", \"\"))\n"
            "| eval vowels=len(replace(lower(query), \"[^aeiou]\", \"\"))\n"
            "| eval consonant_ratio=if(vowels>0, consonants/vowels, 99)\n"
            "| where domain_len > 15 AND consonant_ratio > 3.5 AND NOT query==\"*microsoft*\"\n"
            "| stats count dc(query) as unique_domains by src_ip\n"
            "| where unique_domains > 10\n"
            "| sort -unique_domains\n"
            "```\n\n"
            "## Detection in Elastic/KQL\n"
            "```kql\n"
            "dns.question.type: A AND\n"
            "NOT dns.resolved_ip: * AND   // NXDOMAIN\n"
            "dns.question.name: *\n"
            "// Filter by entropy using scripted field or ML\n"
            "```\n\n"
            "## Automated DGA Classifiers\n"
            "- **Cisco Umbrella** — built-in DGA detection\n"
            "- **MISP DGA feeds** — feeds with known DGA domains\n"
            "- **DGA Detective (open-source)** — ML model for DGA classification\n"
            "- **Virustotal domains** — 'malicious' + 'DGA' category\n\n"
            "## Response\n"
            "1. Identify hosts with high NXDOMAIN rates (>50 unique NXDOMAIN in 1 hour)\n"
            "2. Extract domain list from host via memory forensics or network capture\n"
            "3. Identify DGA family using DGA Detective or `dga-predict` Python library\n"
            "4. Block the IP resolved by the working DGA domain at firewall level\n"
            "5. Isolate infected host, run EDR full scan, collect memory image"
        ),
    },
    # ── HASH IOCS ──────────────────────────────────────────────────────────────────
    {
        "category": "hash_ioc",
        "user": "I have a suspicious file hash: SHA256 3395856ce81f2b7382dee72602f798b642f14140. How do I analyze it?",
        "assistant": (
            "# Threat Intelligence Report — File Hash\n\n"
            "## Indicator Classification\n"
            "**Type:** File Hash (appears to be SHA1 — 40 hex chars)\n"
            "**Note:** The hash `3395856ce81f2b7382dee72602f798b642f14140` is a **well-known test hash** "
            "(EICAR test file signature). It is used to verify AV detection. "
            "Replace with your actual hash for real analysis.\n\n"
            "## Hash Enrichment Process\n\n"
            "**Step 1: VirusTotal Lookup**\n"
            "```bash\n"
            "# API lookup\n"
            "curl 'https://www.virustotal.com/api/v3/files/<SHA256>' \\\n"
            "  -H 'x-apikey: YOUR_VT_KEY' | python3 -m json.tool\n\n"
            "# Key fields to check:\n"
            "# .data.attributes.last_analysis_stats.malicious  → detection count\n"
            "# .data.attributes.names                         → known filenames\n"
            "# .data.attributes.magic                         → file type\n"
            "# .data.attributes.tags                          → 'peexe', 'upx', 'signed'\n"
            "# .data.attributes.signature_info                → code signing\n"
            "```\n\n"
            "**Step 2: Multi-Source Enrichment**\n"
            "```bash\n"
            "# MalwareBazaar (free)\n"
            "curl 'https://mb-api.abuse.ch/api/v1/' \\\n"
            "  -d 'query=get_info&hash=<SHA256>'\n\n"
            "# Hybrid Analysis (free sandbox)\n"
            "curl 'https://www.hybrid-analysis.com/api/v2/search/hash' \\\n"
            "  -H 'api-key: YOUR_KEY' \\\n"
            "  -d 'hash=<SHA256>'\n\n"
            "# ANY.RUN (interactive sandbox)\n"
            "# Upload via: https://app.any.run/\n"
            "```\n\n"
            "**Step 3: OSINT Context**\n"
            "Check for:\n"
            "- Known malware family name (AV detections)\n"
            "- Associated C2 infrastructure (from sandbox reports)\n"
            "- File name(s) used in the wild\n"
            "- First/last seen dates\n"
            "- MITRE ATT&CK mapping (from sandbox behavior)\n\n"
            "**Step 4: PE Analysis (if EXE/DLL)**\n"
            "```bash\n"
            "# PEStudio / pestool\n"
            "pestool --all malware.exe\n\n"
            "# Static analysis with FLOSS (string extraction)\n"
            "floss malware.exe --no-progress\n\n"
            "# Import hash (imphash) — fingerprints compiler/linker\n"
            "python3 -c \"import pefile; p=pefile.PE('malware.exe'); print(p.get_imphash())\"\n"
            "```\n\n"
            "## Disposition Matrix\n"
            "| VT Detections | Action |\n"
            "|---------------|--------|\n"
            "| 50+/72 | Confirmed malware — block hash, isolate host, escalate |\n"
            "| 20–49 | High confidence — block + investigate |\n"
            "| 5–19 | Suspicious — sandbox detonate + investigate |\n"
            "| 1–4 | Inconclusive — sandbox detonate + context analysis |\n"
            "| 0 (first seen <7 days) | Zero-day risk — sandbox + behavioral analysis |\n"
            "| 0 (old, signed) | Likely benign — verify signature and context |"
        ),
    },
    {
        "category": "hash_ioc",
        "user": "What's the difference between MD5, SHA1, SHA256, and fuzzy hashes like ssdeep for malware analysis?",
        "assistant": (
            "# Hash Types in Malware Analysis — Complete Reference\n\n"
            "## Cryptographic Hashes (Exact Match)\n\n"
            "| Hash | Length | Speed | Collision Resistant | Common Use |\n"
            "|------|--------|-------|---------------------|------------|\n"
            "| **MD5** | 32 hex (128-bit) | Fastest | ❌ Broken | Legacy TI feeds, quick lookup |\n"
            "| **SHA1** | 40 hex (160-bit) | Fast | ❌ Theoretical breaks | Older TI databases, YARA |\n"
            "| **SHA256** | 64 hex (256-bit) | Moderate | ✅ Strong | Gold standard: VT, MalwareBazaar, EDR |\n"
            "| **SHA512** | 128 hex | Slower | ✅ Very Strong | Rare in TI, file integrity |\n\n"
            "**Key property:** Exact hash match only — one bit difference = completely different hash. "
            "Malware authors bypass by recompiling → different hash, same behavior.\n\n"
            "## Fuzzy / Similarity Hashes\n\n"
            "**ssdeep (CTPH — Context-Triggered Piecewise Hashing)**\n"
            "```bash\n"
            "# Install\n"
            "apt install ssdeep\n\n"
            "# Generate hash\n"
            "ssdeep malware.exe\n\n"
            "# Compare similarity (0-100%, 100=identical)\n"
            "ssdeep -lrm known_malware.exe unknown.exe\n"
            "# Output: 87% match → likely same malware family\n"
            "```\n\n"
            "**tlsh (Trend Micro Locality Sensitive Hash)**\n"
            "```bash\n"
            "# Better than ssdeep for malware clustering\n"
            "tlsh -f malware.exe\n"
            "tlsh -c malware1.exe malware2.exe  # distance score: 0=identical, <100=similar\n"
            "```\n\n"
            "**imphash (Import Hash — PE files only)**\n"
            "```python\n"
            "import pefile\n"
            "pe = pefile.PE('malware.exe')\n"
            "print(pe.get_imphash())  # fingerprints DLL imports\n"
            "# Same malware family compiled differently often shares imphash\n"
            "```\n\n"
            "**richhash (Rich PE header)**\n"
            "- Fingerprints the compiler/linker toolchain\n"
            "- Can cluster malware built with the same build environment\n"
            "- VirusTotal shows this in PE analysis section\n\n"
            "## When to Use Which\n"
            "| Scenario | Hash to Use |\n"
            "|----------|-------------|\n"
            "| Block in EDR/AV | SHA256 |\n"
            "| Search threat intel databases | SHA256 → MD5 fallback |\n"
            "| Find malware variants/family | ssdeep, tlsh |\n"
            "| Cluster similar PE samples | imphash, richhash |\n"
            "| YARA rule development | SHA256 in meta, imphash in condition |\n\n"
            "**Pro tip:** Always collect all four (MD5, SHA1, SHA256, imphash) when analyzing a sample. "
            "Different TI sources index different hash types."
        ),
    },
    # ── EMAIL IOCS ───────────────────────────────────────────────────────────────
    {
        "category": "email_ioc",
        "user": "How do I analyze a suspicious phishing email for IOCs?",
        "assistant": (
            "# Phishing Email IOC Analysis — Step-by-Step\n\n"
            "## Step 1: Safe Email Handling\n"
            "```bash\n"
            "# Export as .eml from Outlook/Gmail (never open attachments directly)\n"
            "# On Linux, open with text editor for header analysis\n"
            "# Use REMnux VM for all attachment analysis\n"
            "```\n\n"
            "## Step 2: Header Analysis\n"
            "```bash\n"
            "# Extract headers from .eml\n"
            "cat phish.eml | grep -iE '^(from|to|subject|received|x-originating|message-id|return-path|reply-to)'\n\n"
            "# Key header IOCs:\n"
            "# Return-Path ≠ From → spoofing indicator\n"
            "# X-Originating-IP → sender's real IP\n"
            "# Reply-To → different domain than From → BEC indicator\n"
            "# Received headers → trace mail path (bottom to top)\n\n"
            "# Parse with mha (Mail Header Analyzer)\n"
            "pip install mail-parser\n"
            "python3 -c \"import mailparser; m=mailparser.parse_from_file('phish.eml'); print(m.headers)\"\n"
            "```\n\n"
            "## Step 3: SPF/DKIM/DMARC Verification\n"
            "```bash\n"
            "# Check SPF\n"
            "dig +short TXT example.com | grep spf\n"
            "# Pass/Fail/Neutral in email headers:\n"
            "# Authentication-Results: spf=fail (attackerdomain.com)\n\n"
            "# Online tools:\n"
            "# MXToolbox: https://mxtoolbox.com/EmailHeaders.aspx\n"
            "# Email Header Analyzer: https://toolbox.googleapps.com/apps/messageheader/\n"
            "```\n\n"
            "## Step 4: URL Extraction and Analysis\n"
            "```bash\n"
            "# Extract URLs from email body\n"
            "cat phish.eml | grep -oE 'https?://[^ >\"]+'\n\n"
            "# Defang URLs before sharing (replace . with [.] and :// with ://)\n"
            "# NEVER click directly — use:\n\n"
            "# URLScan.io (passive scan)\n"
            "curl 'https://urlscan.io/api/v1/scan/' \\\n"
            "  -H 'API-Key: YOUR_KEY' \\\n"
            "  -d '{\"url\": \"http://suspicious-url.com\", \"visibility\": \"private\"}'\n\n"
            "# VirusTotal URL check\n"
            "curl 'https://www.virustotal.com/api/v3/urls' \\\n"
            "  -H 'x-apikey: YOUR_VT_KEY' \\\n"
            "  --data-urlencode 'url=http://suspicious-url.com'\n"
            "```\n\n"
            "## Step 5: Attachment Analysis\n"
            "```bash\n"
            "# Calculate hash (without opening)\n"
            "sha256sum attachment.docx\n\n"
            "# Check hash on VT\n"
            "# Detonate in sandbox: https://app.any.run/, https://www.hybrid-analysis.com/\n\n"
            "# Extract macros from Office documents\n"
            "pip install oletools\n"
            "olevba attachment.docm\n"
            "```\n\n"
            "## IOC Extraction Checklist\n"
            "- [ ] Sender email address\n"
            "- [ ] Reply-To address (if different)\n"
            "- [ ] X-Originating-IP\n"
            "- [ ] Sending mail server IP (last Received header)\n"
            "- [ ] All URLs in body and headers\n"
            "- [ ] Attachment SHA256 hashes\n"
            "- [ ] Domain(s) used\n"
            "- [ ] Any phone numbers or BEC account info"
        ),
    },
    # ── URL IOCS ──────────────────────────────────────────────────────────────────
    {
        "category": "url_ioc",
        "user": "A URL was flagged: http://192.168.1.200/wp-content/uploads/2024/shell.php — What does this indicate?",
        "assistant": (
            "# Threat Intelligence Report — URL IOC\n\n"
            "## Indicator Classification\n"
            "**Type:** URL\n"
            "**Category:** Web Shell — PHP Remote Code Execution\n"
            "**Risk Score: 10/10**\n\n"
            "## Analysis\n"
            "This URL exhibits **critical web shell indicators:**\n\n"
            "1. **`/wp-content/uploads/`** — WordPress file upload directory. "
            "This is a **well-known web shell deployment path**. The uploads directory is writable "
            "by the web server and served as static files — perfect for shell upload post-exploitation.\n\n"
            "2. **`shell.php`** — Explicit PHP web shell filename. No legitimate file would be named `shell.php`.\n\n"
            "3. **RFC 1918 IP (192.168.x.x)** — Internal IP indicates this server is on your network. "
            "This is an **internal compromise**, not an external indicator.\n\n"
            "## MITRE ATT&CK Mapping\n"
            "| Technique | ID | Description |\n"
            "|-----------|-----|-------------|\n"
            "| Server Software Component: Web Shell | T1505.003 | PHP web shell planted in uploads dir |\n"
            "| Exploit Public-Facing Application | T1190 | WordPress file upload vulnerability |\n"
            "| Command and Scripting Interpreter: PHP | T1059.006 | PHP execution via web shell |\n\n"
            "## Immediate Response Actions\n"
            "1. **ISOLATE the server immediately** — this is an active compromise\n"
            "2. **Do NOT delete the file yet** — preserve forensic evidence first\n"
            "3. **Block web access** to `/wp-content/uploads/` PHP execution at WAF/nginx:\n"
            "   ```nginx\n"
            "   location ~* /wp-content/uploads/.*\\.php$ {\n"
            "       deny all;\n"
            "       return 403;\n"
            "   }\n"
            "   ```\n"
            "4. **Preserve evidence:**\n"
            "   ```bash\n"
            "   sha256sum shell.php; cp shell.php /evidence/shell.php.bak\n"
            "   tar czf /evidence/uploads_$(date +%F).tar.gz /var/www/html/wp-content/uploads/\n"
            "   ```\n"
            "5. **Review web server access logs** for requests to this shell:\n"
            "   ```bash\n"
            "   grep 'shell.php' /var/log/nginx/access.log | grep -v '404'\n"
            "   # Note: attacker source IPs, User-Agents, POST parameters\n"
            "   ```\n"
            "6. **Check for other web shells** in uploads directory:\n"
            "   ```bash\n"
            "   find /var/www/html/wp-content/uploads/ -name '*.php' -newer /var/www/html/wp-config.php\n"
            "   yara64 -r webshell.yar /var/www/html/wp-content/uploads/\n"
            "   ```\n\n"
            "## Disposition\n"
            "**CRITICAL — Active Compromise. Initiate Incident Response immediately.**"
        ),
    },
    # ── THREAT INTEL FEEDS ────────────────────────────────────────────────────────
    {
        "category": "threat_intel",
        "user": "What are the best free threat intelligence feeds I can integrate into my SIEM?",
        "assistant": (
            "# Free Threat Intelligence Feeds — SIEM Integration Guide\n\n"
            "## Top Free TI Feeds by Category\n\n"
            "### IP/Network Blocklists\n"
            "| Feed | URL | Update Freq | Format |\n"
            "|------|-----|-------------|--------|\n"
            "| Spamhaus DROP/EDROP | spamhaus.org/drop | Daily | TXT |\n"
            "| Emerging Threats (ET) | rules.emergingthreats.net | Daily | Various |\n"
            "| CINS Score | cinsscore.com/list/ci-badguys.txt | Daily | TXT |\n"
            "| Abuse.ch Feodo | feodotracker.abuse.ch/downloads/ipblocklist.csv | Multiple/day | CSV |\n"
            "| URLhaus IP | urlhaus.abuse.ch/downloads/csv/ | Multiple/day | CSV |\n"
            "| AlienVault OTX | otx.alienvault.com (API) | Realtime | JSON |\n\n"
            "### Domain/URL Feeds\n"
            "| Feed | URL | Notes |\n"
            "|------|-----|-------|\n"
            "| Abuse.ch URLhaus | urlhaus-api.abuse.ch | Active malware URLs |\n"
            "| PhishTank | phishtank.org/developer_info.php | Phishing URLs |\n"
            "| OpenPhish | openphish.com/feed.txt | Phishing URLs |\n"
            "| Cisco Talos BL | talosintelligence.com/documents/ip-blacklist | IP + domains |\n"
            "| Malware Domain List | malwaredomainlist.com | Domain IOCs |\n\n"
            "### Hash/Malware Feeds\n"
            "| Feed | URL | Notes |\n"
            "|------|-----|-------|\n"
            "| MalwareBazaar | bazaar.abuse.ch/api/ | Recent malware hashes |\n"
            "| VirusShare | virusshare.com | Hashes (registration required) |\n"
            "| Malpedia | malpedia.caad.fkie.fraunhofer.de | Malware family intelligence |\n\n"
            "### Vulnerability/CVE Feeds\n"
            "| Feed | URL | Notes |\n"
            "|------|-----|-------|\n"
            "| CISA KEV | cisa.gov/known-exploited-vulnerabilities-catalog | Known exploited CVEs |\n"
            "| NVD | nvd.nist.gov/vuln/data-feeds | All CVEs + CVSS |\n"
            "| VulnDB (free tier) | vuldb.com | Vulnerability intelligence |\n\n"
            "## SIEM Integration Examples\n\n"
            "**Splunk — Threat Intel Framework (STIX/TAXII):**\n"
            "```conf\n"
            "# In inputs.conf — poll URLhaus feed\n"
            "[script://./bin/fetch_ti.py]\n"
            "interval = 3600\n"
            "sourcetype = threat_intel:urlhaus\n"
            "```\n\n"
            "**Elastic — MISP integration:**\n"
            "```yaml\n"
            "# In Elastic MISP integration settings\n"
            "misp_url: https://your-misp-instance.com\n"
            "misp_key: YOUR_API_KEY\n"
            "fetch_interval: 1h\n"
            "```\n\n"
            "**MISP (free open-source TI platform):**\n"
            "```bash\n"
            "# Self-host MISP and subscribe to free feeds\n"
            "# docker-compose up -d  (via MISP Docker)\n"
            "# Subscribe to: CIRCL OSINT Feed, Abuse.ch, MITRE ATT&CK\n"
            "```\n\n"
            "## Integration Architecture\n"
            "```\n"
            "TI Feeds → MISP (normalize + deduplicate) → SIEM lookup tables\n"
            "                                          → EDR block lists\n"
            "                                          → Firewall deny lists\n"
            "                                          → DNS sinkhole/RPZ\n"
            "```"
        ),
    },
]


def generate():
    samples = []
    for item in KB:
        samples.append({
            "messages": [
                {"role": "system",    "content": HANCOCK_SYSTEM},
                {"role": "user",      "content": item["user"]},
                {"role": "assistant", "content": item["assistant"]},
            ]
        })
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        json.dump(samples, f, indent=2)
    print(f"[ioc_kb] ✅ {len(samples)} samples → {OUTPUT_FILE}")
    return samples


if __name__ == "__main__":
    generate()
