"""
Sigma Detection Rule Knowledge Base — Hancock CyberViser
Q&A pairs for Sigma rule authoring and detection engineering.
Outputs: data/raw_sigma_kb.json
"""
import json
from pathlib import Path

OUTPUT_FILE = Path(__file__).parent.parent / "data" / "raw_sigma_kb.json"

HANCOCK_SYSTEM = (
    "You are Hancock Sigma, CyberViser's expert detection engineer specializing in Sigma rule authoring. "
    "Your expertise covers Sigma rule syntax, log sources (Windows, Linux, cloud, EDR), "
    "MITRE ATT&CK tagging, detection logic, and false positive analysis. "
    "You always output valid, well-formed Sigma YAML with all required fields, "
    "correct ATT&CK tags, falsepositives, and level. Every rule you write is ready to deploy."
)

KB = [
    # ── SIGMA BASICS ─────────────────────────────────────────────────────────────
    {
        "category": "sigma_basics",
        "user": "What is the structure of a Sigma rule? Show me all required and optional fields.",
        "assistant": (
            "**Sigma Rule Structure — Complete Reference**\n\n"
            "```yaml\n"
            "title: Human-readable rule name\n"
            "id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx  # UUID v4 — generate with: python -c \"import uuid; print(uuid.uuid4())\"\n"
            "status: stable  # stable | test | experimental | deprecated | unsupported\n"
            "description: What this rule detects and why it matters\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/TXXXX/\n"
            "  - https://github.com/SigmaHQ/sigma/wiki\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "modified: 2025-01-15\n"
            "tags:\n"
            "  - attack.initial_access         # tactic (lowercase)\n"
            "  - attack.t1566.001              # technique.sub-technique\n"
            "  - attack.t1059                  # technique only (no sub)\n"
            "logsource:\n"
            "  category: process_creation      # OR product + service below\n"
            "  product: windows                # windows | linux | macos\n"
            "  # service: security             # for specific Windows event channels\n"
            "detection:\n"
            "  selection:\n"
            "    Image|endswith:\n"
            "      - '\\\\cmd.exe'\n"
            "      - '\\\\powershell.exe'\n"
            "    CommandLine|contains:\n"
            "      - '-EncodedCommand'\n"
            "      - '-enc '\n"
            "  filter_main:\n"
            "    ParentImage|startswith: 'C:\\\\Program Files\\\\'\n"
            "  condition: selection and not filter_main\n"
            "falsepositives:\n"
            "  - Legitimate admin scripts using encoded commands\n"
            "  - Software installers\n"
            "level: medium  # informational | low | medium | high | critical\n"
            "fields:\n"
            "  - Image\n"
            "  - CommandLine\n"
            "  - ParentImage\n"
            "  - User\n"
            "```\n\n"
            "**Key Detection Modifiers**\n"
            "| Modifier | Example | Meaning |\n"
            "|----------|---------|----------|\n"
            "| `contains` | `cmd\\|contains: 'passwd'` | substring match |\n"
            "| `startswith` | `Image\\|startswith: 'C:\\\\Windows'` | prefix |\n"
            "| `endswith` | `Image\\|endswith: '\\\\cmd.exe'` | suffix |\n"
            "| `re` | `cmd\\|re: '(?i)base64'` | regex |\n"
            "| `contains\\|all` | multi-value AND |\n"
            "| `contains\\|windash` | matches `-` and `/` variants |\n"
            "| `base64offset\\|contains` | detects in base64-encoded args |\n\n"
            "**Condition operators:** `and`, `or`, `not`, `1 of`, `all of`, `| count()`, `| near`"
        ),
    },
    {
        "category": "sigma_basics",
        "user": "Write a Sigma rule to detect PowerShell encoded command execution.",
        "assistant": (
            "```yaml\n"
            "title: PowerShell Encoded Command Execution\n"
            "id: f83a30c6-7fa8-4d39-a98c-1f4fcd6b2a3e\n"
            "status: stable\n"
            "description: |\n"
            "  Detects PowerShell execution with encoded command parameter, commonly used\n"
            "  to obfuscate malicious scripts and bypass command-line logging inspection.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1059/001/\n"
            "  - https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.execution\n"
            "  - attack.t1059.001\n"
            "  - attack.defense_evasion\n"
            "  - attack.t1027\n"
            "logsource:\n"
            "  category: process_creation\n"
            "  product: windows\n"
            "detection:\n"
            "  selection_img:\n"
            "    Image|endswith:\n"
            "      - '\\\\powershell.exe'\n"
            "      - '\\\\pwsh.exe'\n"
            "  selection_cli:\n"
            "    CommandLine|contains:\n"
            "      - ' -EncodedCommand '\n"
            "      - ' -encodedcommand '\n"
            "      - ' -enc '\n"
            "      - ' -en '\n"
            "      - ' -e '\n"
            "  filter_sccm:\n"
            "    ParentImage|contains:\n"
            "      - '\\\\CCM\\\\'\n"
            "      - '\\\\SCCM\\\\'\n"
            "  filter_msi:\n"
            "    ParentImage|endswith: '\\\\msiexec.exe'\n"
            "  condition: all of selection_* and not 1 of filter_*\n"
            "falsepositives:\n"
            "  - SCCM/ConfigMgr software deployment\n"
            "  - Legitimate admin tooling using encoded commands (e.g., some monitoring agents)\n"
            "  - Software installers that use PowerShell for setup\n"
            "level: high\n"
            "fields:\n"
            "  - Image\n"
            "  - CommandLine\n"
            "  - ParentImage\n"
            "  - User\n"
            "  - HostName\n"
            "```\n\n"
            "**What this detects:** PowerShell launched with `-EncodedCommand` (or short forms `-enc`, `-en`, `-e`), "
            "which is commonly used by malware, commodity loaders, and C2 frameworks to hide their payload from "
            "command-line logging.\n\n"
            "**Tuning:** The `-e` short form generates many false positives in some environments. "
            "Start with `-EncodedCommand` and `-enc`, then tune in `-e` carefully after baselining. "
            "Enable PowerShell Script Block Logging (Event ID 4104) for deeper visibility into decoded content."
        ),
    },
    {
        "category": "sigma_detection",
        "user": "Write a Sigma rule to detect LSASS memory dumping.",
        "assistant": (
            "```yaml\n"
            "title: LSASS Memory Dumping via Process Access\n"
            "id: a28c5d9e-2f3b-4c1a-9e8d-7b6f0c4e2a1d\n"
            "status: stable\n"
            "description: |\n"
            "  Detects process access to LSASS memory, commonly used to dump credentials.\n"
            "  Tools: Mimikatz, ProcDump, Task Manager, Comsvcs.dll MiniDump, Cobalt Strike hashdump.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1003/001/\n"
            "  - https://lolbas-project.github.io/lolbas/Libraries/Comsvcs/\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.credential_access\n"
            "  - attack.t1003.001\n"
            "logsource:\n"
            "  category: process_access\n"
            "  product: windows\n"
            "detection:\n"
            "  selection:\n"
            "    TargetImage|endswith: '\\\\lsass.exe'\n"
            "    GrantedAccess|contains:\n"
            "      - '0x1010'   # PROCESS_VM_READ | PROCESS_QUERY_LIMITED_INFORMATION\n"
            "      - '0x1410'   # PROCESS_VM_READ | PROCESS_QUERY_INFORMATION | PROCESS_DUP_HANDLE\n"
            "      - '0x1fffff' # PROCESS_ALL_ACCESS\n"
            "      - '0x143a'   # used by Cobalt Strike\n"
            "  filter_sysmon:\n"
            "    SourceImage|startswith:\n"
            "      - 'C:\\\\Windows\\\\System32\\\\'\n"
            "      - 'C:\\\\Windows\\\\SysWOW64\\\\'\n"
            "    SourceImage|endswith:\n"
            "      - '\\\\werfault.exe'\n"
            "      - '\\\\WerFaultSecure.exe'\n"
            "      - '\\\\msseces.exe'\n"
            "  filter_av:\n"
            "    SourceImage|contains:\n"
            "      - '\\\\CrowdStrike\\\\'\n"
            "      - '\\\\SentinelOne\\\\'\n"
            "      - '\\\\Carbon Black\\\\'\n"
            "  condition: selection and not 1 of filter_*\n"
            "falsepositives:\n"
            "  - Antivirus/EDR products legitimately accessing LSASS\n"
            "  - Windows Error Reporting (werfault.exe)\n"
            "  - Some diagnostic tools and performance monitors\n"
            "  - LSASS protection software (e.g., Credential Guard validators)\n"
            "level: high\n"
            "fields:\n"
            "  - SourceImage\n"
            "  - TargetImage\n"
            "  - GrantedAccess\n"
            "  - CallTrace\n"
            "```\n\n"
            "**Detection note:** Requires Sysmon Event ID 10 (ProcessAccess). "
            "Log source `process_access` maps to Sysmon EID 10. "
            "Also write a complementary rule for `comsvcs.dll MiniDump` via process_creation: "
            "look for `rundll32.exe` with CommandLine containing `comsvcs` and `MiniDump`."
        ),
    },
    {
        "category": "sigma_detection",
        "user": "Write a Sigma rule to detect DCSync attacks.",
        "assistant": (
            "```yaml\n"
            "title: DCSync Attack via Directory Service Access\n"
            "id: b76e3f12-9d4a-4b2e-8c1f-6a3d5e7b9c2f\n"
            "status: stable\n"
            "description: |\n"
            "  Detects DCSync attacks where an attacker replicates AD secrets using\n"
            "  DS-Replication-Get-Changes-All rights. Tools: Mimikatz lsadump::dcsync,\n"
            "  Impacket secretsdump.py. Requires Windows Security auditing: Directory Service Access.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1003/006/\n"
            "  - https://adsecurity.org/?p=1729\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.credential_access\n"
            "  - attack.t1003.006\n"
            "logsource:\n"
            "  product: windows\n"
            "  service: security\n"
            "detection:\n"
            "  selection:\n"
            "    EventID: 4662\n"
            "    Properties|contains:\n"
            "      - '1131f6aa-9c07-11d1-f79f-00c04fc2dcd2'  # DS-Replication-Get-Changes-All\n"
            "      - '1131f6ad-9c07-11d1-f79f-00c04fc2dcd2'  # DS-Replication-Get-Changes-In-Filtered-Set\n"
            "      - '89e95b76-444d-4c62-991a-0facbeda640c'  # DS-Replication-Get-Changes\n"
            "    AccessMask: '0x100'  # WRITE_OWNER or replication access\n"
            "  filter_legitimate_dc:\n"
            "    SubjectDomainName: '%SystemDomain%'  # Filter out DC-to-DC replication\n"
            "    SubjectUserName|endswith: '$'         # Computer accounts (DCs)\n"
            "  filter_aad:\n"
            "    SubjectUserName|startswith: 'MSOL_'  # Azure AD Connect service account\n"
            "  condition: selection and not 1 of filter_*\n"
            "falsepositives:\n"
            "  - Azure AD Connect (MSOL_ accounts) — filter by SubjectUserName\n"
            "  - Domain Controller-to-DC replication (computer accounts ending in $)\n"
            "  - Legitimate AD backup/migration tools\n"
            "level: critical\n"
            "fields:\n"
            "  - SubjectUserName\n"
            "  - SubjectDomainName\n"
            "  - ObjectDN\n"
            "  - Properties\n"
            "  - AccessMask\n"
            "```\n\n"
            "**Required audit policy:** Enable 'Directory Service Access' in Windows Advanced Audit Policy. "
            "This is not enabled by default. Configure via GPO: Computer Configuration → "
            "Windows Settings → Security Settings → Advanced Audit Policy → DS Access → "
            "Audit Directory Service Access.\n\n"
            "**SIEM correlation:** Correlate with Mimikatz indicators (Event 7036 service starts), "
            "anomalous logon patterns from the account, and process creation events."
        ),
    },
    {
        "category": "sigma_detection",
        "user": "Write a Sigma rule for detecting suspicious scheduled task creation.",
        "assistant": (
            "```yaml\n"
            "title: Suspicious Scheduled Task Creation via Command Line\n"
            "id: c4d1e8a3-7f2b-4d5e-9a6c-1b3f8d0e4c7a\n"
            "status: stable\n"
            "description: |\n"
            "  Detects scheduled task creation via schtasks.exe with suspicious parameters\n"
            "  commonly used for persistence: running from temp/user dirs, executing scripts,\n"
            "  or using LOLBin execution methods.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1053/005/\n"
            "  - https://lolbas-project.github.io/lolbas/Binaries/Schtasks/\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.persistence\n"
            "  - attack.execution\n"
            "  - attack.t1053.005\n"
            "logsource:\n"
            "  category: process_creation\n"
            "  product: windows\n"
            "detection:\n"
            "  selection_create:\n"
            "    Image|endswith: '\\\\schtasks.exe'\n"
            "    CommandLine|contains:\n"
            "      - '/create'\n"
            "      - '-create'\n"
            "  selection_suspicious_path:\n"
            "    CommandLine|contains:\n"
            "      - '\\\\Temp\\\\'\n"
            "      - '\\\\AppData\\\\'\n"
            "      - '\\\\ProgramData\\\\'\n"
            "      - '\\\\Users\\\\Public\\\\'\n"
            "      - '%TEMP%'\n"
            "      - '%APPDATA%'\n"
            "  selection_suspicious_exec:\n"
            "    CommandLine|contains:\n"
            "      - 'powershell'\n"
            "      - 'cmd.exe'\n"
            "      - 'wscript'\n"
            "      - 'cscript'\n"
            "      - 'mshta'\n"
            "      - 'regsvr32'\n"
            "      - 'rundll32'\n"
            "      - 'certutil'\n"
            "      - 'bitsadmin'\n"
            "  filter_legitimate:\n"
            "    ParentImage|contains:\n"
            "      - '\\\\Microsoft\\\\'\n"
            "      - '\\\\Windows\\\\'\n"
            "    ParentImage|endswith:\n"
            "      - '\\\\msiexec.exe'\n"
            "      - '\\\\services.exe'\n"
            "  condition: selection_create and (selection_suspicious_path or selection_suspicious_exec) and not filter_legitimate\n"
            "falsepositives:\n"
            "  - Software installers creating legitimate scheduled tasks\n"
            "  - IT admin scripts automating maintenance tasks\n"
            "  - Backup software using schtasks for scheduling\n"
            "level: high\n"
            "fields:\n"
            "  - Image\n"
            "  - CommandLine\n"
            "  - ParentImage\n"
            "  - ParentCommandLine\n"
            "  - User\n"
            "```\n\n"
            "**Complement with Event ID 4698** (A scheduled task was created) from Windows Security log:\n"
            "```yaml\n"
            "logsource:\n"
            "  product: windows\n"
            "  service: security\n"
            "detection:\n"
            "  selection:\n"
            "    EventID: 4698\n"
            "    TaskContent|contains:\n"
            "      - 'powershell'\n"
            "      - 'cmd.exe'\n"
            "      - 'mshta'\n"
            "  condition: selection\n"
            "```"
        ),
    },
    {
        "category": "sigma_detection",
        "user": "Write a Sigma rule to detect Kerberoasting attacks.",
        "assistant": (
            "```yaml\n"
            "title: Kerberoasting — Suspicious Kerberos TGS Request\n"
            "id: d2e5f8c1-4a7b-4f3d-8c2e-9b1a6d4e7f0c\n"
            "status: stable\n"
            "description: |\n"
            "  Detects Kerberoasting: requesting Kerberos TGS tickets for service accounts\n"
            "  with RC4 encryption (etype 23) which can be brute-forced offline.\n"
            "  Requires: Security audit 'Kerberos Service Ticket Operations' enabled.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1558/003/\n"
            "  - https://www.harmj0y.net/blog/powershell/kerberoasting-without-mimikatz/\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.credential_access\n"
            "  - attack.t1558.003\n"
            "logsource:\n"
            "  product: windows\n"
            "  service: security\n"
            "detection:\n"
            "  selection:\n"
            "    EventID: 4769\n"
            "    ServiceName|endswith: '$'\n"
            "    TicketEncryptionType: '0x17'  # RC4_HMAC_MD5 — crackable\n"
            "    TicketOptions: '0x40800000'   # forwardable ticket request\n"
            "  filter_computer_accounts:\n"
            "    ServiceName|startswith: 'krbtgt'\n"
            "  filter_dc:\n"
            "    IpAddress: '::1'  # localhost — DC self-service\n"
            "  condition: selection and not 1 of filter_*\n"
            "falsepositives:\n"
            "  - Legacy applications that don't support AES Kerberos encryption\n"
            "  - Older service accounts not configured for AES\n"
            "  - Network monitoring or vulnerability scanners\n"
            "level: medium\n"
            "fields:\n"
            "  - ServiceName\n"
            "  - AccountName\n"
            "  - IpAddress\n"
            "  - TicketEncryptionType\n"
            "```\n\n"
            "**Detection tuning:** High-value targets (many etype 0x17 requests in short period) "
            "suggest automated Kerberoasting (Rubeus, Impacket GetUserSPNs). "
            "Complement with: correlation rule for >5 EID 4769 events from same IP in 60 seconds.\n\n"
            "**Remediation:** Convert all service accounts to AES encryption using: "
            "`Set-ADUser -Identity <svc_acct> -KerberosEncryptionType AES128,AES256`"
        ),
    },
    {
        "category": "sigma_cloud",
        "user": "Write a Sigma rule to detect AWS CloudTrail: IAM privilege escalation.",
        "assistant": (
            "```yaml\n"
            "title: AWS IAM Privilege Escalation via Policy Attachment\n"
            "id: e1f4b9c2-3d6a-4e5f-7b8c-2a9d1e6f3c0b\n"
            "status: stable\n"
            "description: |\n"
            "  Detects AWS IAM privilege escalation techniques: attaching admin policies,\n"
            "  creating new admin users, or updating inline policies to grant elevated access.\n"
            "  Commonly used in post-compromise cloud lateral movement.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1098/003/\n"
            "  - https://bishopfox.com/blog/privilege-escalation-in-aws\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.privilege_escalation\n"
            "  - attack.t1098.003\n"
            "  - attack.persistence\n"
            "  - attack.t1136.003\n"
            "logsource:\n"
            "  product: aws\n"
            "  service: cloudtrail\n"
            "detection:\n"
            "  selection_attach_admin:\n"
            "    eventSource: iam.amazonaws.com\n"
            "    eventName:\n"
            "      - AttachUserPolicy\n"
            "      - AttachGroupPolicy\n"
            "      - AttachRolePolicy\n"
            "    requestParameters.policyArn|contains:\n"
            "      - 'AdministratorAccess'\n"
            "      - 'PowerUserAccess'\n"
            "      - 'IAMFullAccess'\n"
            "  selection_create_admin_user:\n"
            "    eventSource: iam.amazonaws.com\n"
            "    eventName: CreateLoginProfile\n"
            "  selection_put_policy:\n"
            "    eventSource: iam.amazonaws.com\n"
            "    eventName: PutUserPolicy\n"
            "    requestParameters.policyDocument|contains: '\"*\"'  # wildcard action\n"
            "  filter_terraform:\n"
            "    userAgent|contains: 'terraform'\n"
            "    sourceIPAddress|startswith: '10.'  # internal CI/CD\n"
            "  condition: (1 of selection_*) and not filter_terraform\n"
            "falsepositives:\n"
            "  - Infrastructure-as-code deployments (Terraform, CloudFormation, CDK)\n"
            "  - Legitimate admin provisioning by cloud ops team\n"
            "  - AWS Organizations automated account vending\n"
            "level: high\n"
            "fields:\n"
            "  - userIdentity.arn\n"
            "  - sourceIPAddress\n"
            "  - userAgent\n"
            "  - requestParameters.policyArn\n"
            "  - requestParameters.userName\n"
            "```\n\n"
            "**Correlate with:** `CreateAccessKey` events for the same user (key exfiltration), "
            "`ConsoleLogin` from unusual IP, and `AssumeRole` chains."
        ),
    },
    {
        "category": "sigma_detection",
        "user": "Write a Sigma rule to detect Pass-the-Hash attacks.",
        "assistant": (
            "```yaml\n"
            "title: Pass-the-Hash Attack via NTLM Network Logon\n"
            "id: f7b2e4d8-6c3a-4f1e-9d2b-8a5c7e3b1f4d\n"
            "status: stable\n"
            "description: |\n"
            "  Detects Pass-the-Hash (PtH) attacks using anomalous NTLM logons.\n"
            "  PtH uses NTLM hashes for authentication without knowing the plaintext password.\n"
            "  Key indicator: NtLmSsp NTLM logon (Type 3) with unusual source workstation.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1550/002/\n"
            "  - https://blog.gentilkiwi.com/securite/mimikatz/pass-the-hash-et-pass-the-ticket\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.lateral_movement\n"
            "  - attack.t1550.002\n"
            "  - attack.defense_evasion\n"
            "  - attack.t1550\n"
            "logsource:\n"
            "  product: windows\n"
            "  service: security\n"
            "detection:\n"
            "  selection:\n"
            "    EventID: 4624\n"
            "    LogonType: 3\n"
            "    AuthenticationPackageName: NTLM\n"
            "    LmPackageName: 'NTLM V2'\n"
            "  filter_local:\n"
            "    IpAddress:\n"
            "      - '127.0.0.1'\n"
            "      - '::1'\n"
            "  filter_anonymous:\n"
            "    TargetUserName: 'ANONYMOUS LOGON'\n"
            "  filter_machine_accounts:\n"
            "    TargetUserName|endswith: '$'\n"
            "  condition: selection and not 1 of filter_*\n"
            "falsepositives:\n"
            "  - Legitimate NTLM network logons in environments without Kerberos\n"
            "  - Legacy applications using NTLM authentication\n"
            "  - Some file share access from Linux/Mac clients\n"
            "level: medium\n"
            "fields:\n"
            "  - TargetUserName\n"
            "  - WorkstationName\n"
            "  - IpAddress\n"
            "  - LogonType\n"
            "  - AuthenticationPackageName\n"
            "```\n\n"
            "**Note:** This rule generates false positives in environments with significant NTLM use. "
            "For better signal, correlate with: unusual source workstation for the account, "
            "logon from IP not matching the account's usual subnet, or lateral movement patterns "
            "(account logging into multiple hosts in short timeframe). "
            "Also monitor EID 4625 (failed NTLM logons) for brute-force PtH spraying."
        ),
    },
    {
        "category": "sigma_detection",
        "user": "Write a Sigma rule to detect Cobalt Strike beacon activity.",
        "assistant": (
            "```yaml\n"
            "title: Cobalt Strike Beacon — Named Pipe Indicators\n"
            "id: a9c3f7e1-2b5d-4c8a-7f1e-3d6b9a4c2e8f\n"
            "status: stable\n"
            "description: |\n"
            "  Detects Cobalt Strike beacon default named pipe patterns used for\n"
            "  inter-process communication in post-exploitation. These pipe names are\n"
            "  configurable but default patterns are common in commodity CS deployments.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1071/004/\n"
            "  - https://redcanary.com/threat-detection-report/threats/cobalt-strike/\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.command_and_control\n"
            "  - attack.t1071.004\n"
            "  - attack.t1090\n"
            "logsource:\n"
            "  product: windows\n"
            "  category: pipe_created\n"
            "detection:\n"
            "  selection:\n"
            "    PipeName|startswith:\n"
            "      - '\\\\MSSE-'\n"
            "      - '\\\\msagent_'\n"
            "      - '\\\\postex_'\n"
            "      - '\\\\postex_ssh_'\n"
            "      - '\\\\status_'\n"
            "      - '\\\\mypipe-f'\n"
            "      - '\\\\mypipe-h'\n"
            "      - '\\\\ntsvcs'\n"
            "      - '\\\\scerpc'\n"
            "  condition: selection\n"
            "falsepositives:\n"
            "  - None expected — these pipe names are Cobalt Strike defaults\n"
            "level: critical\n"
            "fields:\n"
            "  - PipeName\n"
            "  - Image\n"
            "  - ProcessId\n"
            "```\n\n"
            "**Complementary rules for broader CS coverage:**\n\n"
            "1. **CS Network beacon** (DNS category): high-freq DNS requests to domains with short TTL\n"
            "2. **CS process injection**: `CreateRemoteThread` into legitimate processes (Sysmon EID 8)\n"
            "3. **CS sleep variation**: periodic HTTP/HTTPS beacons with jitter (netconn to single IP)\n"
            "4. **CS named pipe connect**: `PipeEvent` with `EventType: CONNECT` to above names\n\n"
            "Requires **Sysmon Event ID 17** (Pipe Created) with PipeEvent logging configured."
        ),
    },
    {
        "category": "sigma_linux",
        "user": "Write a Sigma rule to detect Linux reverse shell activity.",
        "assistant": (
            "```yaml\n"
            "title: Linux Reverse Shell via Bash or Python\n"
            "id: b5d8e2f4-9c1a-4e7b-8d3f-6a2c5e1b9d4f\n"
            "status: stable\n"
            "description: |\n"
            "  Detects common reverse shell one-liners on Linux executed via bash, python,\n"
            "  nc/ncat, socat, or perl. These patterns are used in exploitation and post-exploitation.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1059/004/\n"
            "  - https://www.revshells.com/\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.execution\n"
            "  - attack.t1059.004\n"
            "  - attack.command_and_control\n"
            "  - attack.t1071\n"
            "logsource:\n"
            "  product: linux\n"
            "  category: process_creation\n"
            "detection:\n"
            "  selection_bash_dev:\n"
            "    CommandLine|contains:\n"
            "      - '/dev/tcp/'\n"
            "      - '/dev/udp/'\n"
            "  selection_nc_exec:\n"
            "    Image|endswith:\n"
            "      - '/nc'\n"
            "      - '/ncat'\n"
            "      - '/netcat'\n"
            "    CommandLine|contains:\n"
            "      - ' -e '\n"
            "      - ' -c '\n"
            "  selection_python_socket:\n"
            "    Image|contains:\n"
            "      - '/python'\n"
            "      - '/python3'\n"
            "    CommandLine|contains:\n"
            "      - 'socket.connect'\n"
            "      - 'subprocess.call'\n"
            "      - 'pty.spawn'\n"
            "  selection_socat:\n"
            "    Image|endswith: '/socat'\n"
            "    CommandLine|contains: 'EXEC:'\n"
            "  selection_perl:\n"
            "    Image|endswith: '/perl'\n"
            "    CommandLine|contains:\n"
            "      - 'socket'\n"
            "      - '/bin/sh'\n"
            "  filter_ctf:\n"
            "    User: 'ctf'\n"
            "  condition: 1 of selection_* and not filter_ctf\n"
            "falsepositives:\n"
            "  - CTF/security research environments\n"
            "  - Legitimate netcat usage without -e (port scanning, debugging)\n"
            "  - Network testing tools in authorized pentests\n"
            "level: high\n"
            "fields:\n"
            "  - Image\n"
            "  - CommandLine\n"
            "  - User\n"
            "  - ParentImage\n"
            "  - ParentCommandLine\n"
            "```\n\n"
            "**Logging requirement:** Requires process auditing on Linux. Enable via:\n"
            "- auditd with `execve` syscall logging, or\n"
            "- Sysmon for Linux, or\n"
            "- EDR agent (CrowdStrike, Wazuh, SentinelOne)"
        ),
    },
    {
        "category": "sigma_detection",
        "user": "Write a Sigma rule to detect lateral movement via PsExec.",
        "assistant": (
            "```yaml\n"
            "title: PsExec Lateral Movement Indicators\n"
            "id: c3f6b9e2-7d4a-4c1f-8e3b-5a2d9c7b1e4f\n"
            "status: stable\n"
            "description: |\n"
            "  Detects PsExec lateral movement using multiple indicators:\n"
            "  service installation, named pipe creation, and ADMIN$ share access.\n"
            "  PsExec installs PSEXESVC.exe as a service on the target.\n"
            "references:\n"
            "  - https://attack.mitre.org/techniques/T1569/002/\n"
            "  - https://docs.microsoft.com/en-us/sysinternals/downloads/psexec\n"
            "author: Hancock / CyberViser\n"
            "date: 2025-01-15\n"
            "tags:\n"
            "  - attack.lateral_movement\n"
            "  - attack.execution\n"
            "  - attack.t1569.002\n"
            "  - attack.t1021.002\n"
            "logsource:\n"
            "  product: windows\n"
            "  service: system\n"
            "detection:\n"
            "  selection_service:\n"
            "    EventID: 7045\n"
            "    ServiceName: 'PSEXESVC'\n"
            "  condition: selection_service\n"
            "falsepositives:\n"
            "  - Legitimate IT admin use of PsExec for remote management\n"
            "  - Authorized remote support tools\n"
            "level: high\n"
            "fields:\n"
            "  - ServiceName\n"
            "  - ServiceFileName\n"
            "  - AccountName\n"
            "```\n\n"
            "**Additional PsExec detection (process_creation):**\n"
            "```yaml\n"
            "detection:\n"
            "  selection:\n"
            "    ParentImage|endswith: '\\\\PSEXESVC.exe'\n"
            "    # OR for attacker-renamed PsExec:\n"
            "  selection_imphash:\n"
            "    # Imphash for PsExec variants (Sysmon)\n"
            "    Imphash:\n"
            "      - 'd5866dbfb2554671e6c30bba26c3f15a'  # PsExec v2.x\n"
            "      - 'b6db3657f0f8a7e5a76e08af1e37038a'\n"
            "```"
        ),
    },
    {
        "category": "sigma_siem",
        "user": "How do I convert a Sigma rule to Splunk, Elastic, and Sentinel queries?",
        "assistant": (
            "**Converting Sigma Rules — Multi-Platform Guide**\n\n"
            "**Using pySigma (recommended for 2024+)**\n"
            "```bash\n"
            "# Install\n"
            "pip install sigma-cli pySigma-backend-splunk pySigma-backend-elasticsearch pySigma-backend-microsoft365defender\n\n"
            "# Convert to Splunk SPL\n"
            "sigma convert -t splunk -p splunk_windows rule.yml\n\n"
            "# Convert to Elastic ESQL\n"
            "sigma convert -t esql -p ecs_windows rule.yml\n\n"
            "# Convert to Microsoft Sentinel (KQL)\n"
            "sigma convert -t microsoft365defender rule.yml\n"
            "# OR for Sentinel Analytics Rule:\n"
            "sigma convert -t sentinelasim rule.yml\n\n"
            "# Convert entire directory\n"
            "sigma convert -t splunk -p splunk_windows rules/windows/\n"
            "```\n\n"
            "**Example Output for PowerShell Encoded Command Rule**\n\n"
            "Splunk SPL:\n"
            "```spl\n"
            "(Image=\"*\\\\powershell.exe\" OR Image=\"*\\\\pwsh.exe\") "
            "(CommandLine=\"* -EncodedCommand *\" OR CommandLine=\"* -enc *\") "
            "NOT (ParentImage=\"*\\\\CCM\\\\*\" OR ParentImage=\"*\\\\SCCM\\\\*\")\n"
            "| table _time, ComputerName, User, Image, CommandLine, ParentImage\n"
            "```\n\n"
            "Elastic KQL:\n"
            "```kql\n"
            "(process.executable : (\"*\\\\powershell.exe\" OR \"*\\\\pwsh.exe\")) AND "
            "(process.command_line : (\"* -EncodedCommand *\" OR \"* -enc *\")) AND NOT "
            "(process.parent.executable : (\"*\\\\CCM\\\\*\" OR \"*\\\\SCCM\\\\*\"))\n"
            "```\n\n"
            "Microsoft Sentinel KQL:\n"
            "```kql\n"
            "DeviceProcessEvents\n"
            "| where FileName in~ ('powershell.exe', 'pwsh.exe')\n"
            "| where ProcessCommandLine has_any ('-EncodedCommand', '-enc ')\n"
            "| where not(InitiatingProcessFolderPath has_any ('CCM', 'SCCM'))\n"
            "| project TimeGenerated, DeviceName, AccountName, FileName, ProcessCommandLine\n"
            "```\n\n"
            "**Backend list:** `sigma list backends` shows all available targets.\n"
            "**Sigma Hub:** https://sigmaHQ.io — browse 3,000+ community rules and test conversions."
        ),
    },
]


def generate():
    samples = []
    for item in KB:
        samples.append({
            "messages": [
                {"role": "system",    "content": HANCOCK_SYSTEM},
                {"role": "user",      "content": item["user"]},
                {"role": "assistant", "content": item["assistant"]},
            ]
        })
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        json.dump(samples, f, indent=2)
    print(f"[sigma_kb] ✅ {len(samples)} samples → {OUTPUT_FILE}")
    return samples


if __name__ == "__main__":
    generate()
